Makefile.am
=> Install the init-mix.sh script

pack_maker.sh
Since delta pack creation is tied to a DevOps workflow, this script
makes more sense to live in the mixer-tools repo, and later be merged
into create-update.sh.
=> Import pack_maker.sh script from swupd-server

update-bundles.sh
While following mixer instructions this script failed on this mkdir line...
=> Fixing mkdir line to be more resilient.

src/builder/builder.go, src/mixer/main.go
=> Improving how commands are organized

src/builder/builder.go
This code change enables the use of Linux Environment
variables in the configuration file. This is very useful
for paths to avoid having to hard-code paths.
For proper use, it will also require a similar patch to
the bundle-chroot-builder project.
Fixes  https://github.com/clearlinux/mixer-tools/issues/28
Signed-off-by: Mark Horn <mark.d.horn@intel.com>
=> Enable Environment Variables in Configuration File

builder/builder.go
Mixer calls ister, that calls swupd (client), that uses a staging
directory to cache downloaded files. If not specified, it defaults to
the system one, which is not what we want, since the system might not
be using the mix we are creating.
Without passing this, build-image works only if there is no conflict
with some previous version (from any stream) that it used before.
Fix based on diagnostic by Tudor and William.
=> builder: create a temp dir and use as stage dir for ister

builder/builder.go
The error was being ignored, now is propagated. Also made some
cleanups in the function (and its comments).
Fixes #45.
=> Fail if signing the MoM fails

swupd/cmd/create-fullfiles/main.go, swupd/create_manifests.go, swupd/create_manifests_test.go, swupd/external.go, swupd/filesystem.go, swupd/fullfiles.go, swupd/fullfiles_test.go, swupd/hash.go, swupd/manifest.go, swupd/manifest_test.go
=> Fix several issues identified by 'make lint'

helpers/helpers.go
=> helpers: remove unused ENOVERSION constant

swupd/cmd/create-fullfiles/main.go
=> swupd: fix vetshadow errors in create-fullfiles test program

swupd/create_manifests_test.go, swupd/helpers_test.go
=> Add test helpers to check for strings in manifests

builder/builder.go, mixer/cmd/build.go, swupd/cmd/create-pack/main.go, swupd/packs.go
=> Add 'mixer build delta-packs' when using --new-swupd

mixer/cmd/root.go
The flag --cpu-profile let the caller specify a filename to write the
CPU profile information to. That can be later read with
$ go tool pprof FILENAME
More details on how to use the tool is in
https://blog.golang.org/profiling-go-programs.
The new flag is hidden from the default help message -- since it is
mostly a feature for developers.
=> mixer: add CPU profiling if flag passed

builder/builder.go
Check for required variables in the builder.conf when reading.
Fixes #63
Signed-off-by: Mark D Horn <mark.d.horn@intel.com>
=> Ensure required builder.conf variables are present

.travis.yml, helpers/helpers.go, swupd/delta.go, swupd/delta_test.go, swupd/helpers_test.go
This isn't hardcoded to use Manifest.Full to be more general, but it should be passed in as the manifest to use for our case.
=> Add delta creation code

swupd/create_manifests_test.go, swupd/manifest.go
If the old file is deleted and within the minVersion copy it over as-is.
Add test as well.
=>  Copy over old deleted files if newer than minVersion

swupd/filesystem.go
=> swupd: add \n to warning printing

swupd/create_manifests_test.go, swupd/manifest.go
Renames must persist so make sure the rename flag from the old manifest
sticks around and is copied into the new manifest.
Link these old renames together before linking new renames. After all
the links are set up deprecate any renames that have lost their link.
These are orphaned renames caused either by rename chains or by deleting
renameTo files.
Add a test to check that renames persist.
=> Deprecate and persist renames properly

builder/builder.go, mixer/cmd/root.go
Support (and default to) "latest" in mixer init clear-version
Adds support for the keyword "latest" for `--clear-version` when
running mixer init. This becomes the default value if the flag is
omitted.
'--clear-version latest' will fetch the latest published upstream
version number, according to the value found via 'upstreamurl'
=> Support (and default to) "latest" in mixer init clear-version

swupd/manifest.go, swupd/packs_test.go
When "unpacking" swupd client look for deltas based on the rename
flag, so use the same logic to pack deltas for it. With these the new
implementation of packs should be on par with the swupd-server.
=> swupd: pack more deltas based on pre-calculated rename flag

swupd/create_manifests_test.go
I had a hunch that ghosted renames weren't working properly. Glad to see
I was wrong.
=> Add another test for ghosted renames

swupd/create_manifests.go, swupd/create_manifests_test.go, swupd/manifest.go
=> Add test for nested includes subtraction

swupd/manifest.go
=> Do not append os-core include twice

swupd/manifest.go
=> Also only set hash to zero when deprecated rename not present

swupd/manifest.go
=> Subtract from file count when subtracting files

builder/builder.go
Account for the size of included bundles for formatting the output of
list.
Before:
```
bootloader     (upstream)
c-basic        (upstream)
desktop        (upstream)
desktop-apps   (upstream) (included)
desktop-assets (upstream) (included)
desktop-gnomelibs (upstream) (included)
desktop-locales (upstream) (included)
kernel-native  (upstream)
libX11client   (upstream) (included)
os-core        (upstream)
os-core-update (upstream)
python3-basic  (upstream) (included)
sysadmin-basic (upstream) (included)
```
After:
```
bootloader        (upstream)
c-basic           (upstream)
desktop           (upstream)
desktop-apps      (upstream) (included)
desktop-assets    (upstream) (included)
desktop-gnomelibs (upstream) (included)
desktop-locales   (upstream) (included)
kernel-native     (upstream) …
```
=> mixer: fix output of list when have included bundles

builder/chroots.go
In particular add a "done" message to help with progress indication
during parallelized chroot builds.
=> Improve progress output for chroot building

builder/builder.go
=> Add a timer to delta pack creation

builder/builder.go, mixer/cmd/rpms.go
=> mixer: update RPMDIR to LOCAL_RPM_DIR

builder/builder.go
=> Add newline to error printf

builder/bundles.go
This file is intended to be used by validation tooling to identify
orphaned packages and verify there are no file collisions in the build.
=> Add os-packages file to list all package/srpms in build

builder/builder.go
This patch updates the 'mixer bundle list' command to read the local and
upstream package files. Now 'mixer bundle list local', for example, will
list package-bundles defined in local-packages alongside bundles defined
in local-bundles/.
=> Fix 'mixer bundle list' to work with packages

builder/builder.go
This patch changes the output for 'mixer bundle list' and 'mixer bundle
list --tree' to distinguish between bundles and packages. This should
help clarify exactly where items in the mix are coming from.
Example output:
```
user@machine ~/mix/test $ mixer init
Creating new builder.conf configuration file...
Initializing mix version 10 from upstream version 21490
Adding bundle "os-core" from upstream bundles
Adding bundle "os-core-update" from upstream bundles
Adding bundle "bootloader" from upstream bundles
Adding bundle "kernel-native" from upstream bundles
```
```
user@machine ~/mix/test $ mixer bundle edit editors --suppress-editor 
user@machine ~/mix/test $ mixer bundle add editors
Adding bundle "editors" from local bundles …
```
=> Update 'mixer bundle list' to report packages

builder/builder.go, builder/format.go, mixer/cmd/build.go
Begin adding support for automating format bumps with mixer.
=> [AFB] Format Bump Support

builder/bundles.go
Fixes https://github.com/clearlinux/mixer-tools/issues/260.
~~This passes my preliminary local testing, but I need to do additional testing with `validate-swupd.sh`.~~
------
Previously, mixer failed to build update content if local and upstream
repositories had a package name collision with different content.
'mixer build bundles' relies on the output of 'dnf repoquery -l' to get
the contents of a given package and 'dnf install' to put the contents
of that package into the full chroot. 'dnf repoquery' does not utilize
the repository prioritization resolver that 'dnf install' does, and
instead lists the contents of every matching package in every repository.
This results in the <bundle>-info file containing the file lists of both
the upstream and the local version of the rpm, but the full …
=> Fix local package name collision bug

builder/bundles.go
Sometimes dnf output will not contain the "Installing:\n" pattern,
e.g. if there is a package that doesn't exist in a bundle, the output
looks like
Last metadata expiration check: 0:00:06 ago on Thu 19 Apr 2018 05:09:16 PM PDT.
No match for argument: libc
and mixer would crash because the Split resulting slice wouldn't have
a second element.
The actual error will be caught later when the install of the "full
chroot" happens, so it is fine for now just ignore it.
Ideally the goroutine handling should be similar to fullfiles, so the
workers have a way to indicate that an error occurred and the program
can finish early. Added that as a TODO.
=> builder: fix panic when trying to build bundles with invalid input

builder/builder.go, mixer/cmd/repos.go
Adds the following commands:
* repo remove
* repo list
* repo init
and makes a couple fixes/improvements to the existing repo add command. See individual commits for more info.
=> Add improved repo manipulation support

bat/tests/04-create-mix-with-custom-content/run.bats, bat/tests/05-create-mix-with-blended-content/run.bats
The old one disappeared, so add one that actually exists... for now.
=> Update RPM url for BAT tests

mixin/build.go
Write a flag file to MIXWS/.valid-mix when a mixer build is successful
so swupd-client will know when the user's mix is in a good state to run
an update from.
The current client implementation just checks if there is more than `.` and `..` under /usr/share/mix to determine if a mix exists and blindly tries to run an update from it. If a mixer build fails there will be other files but the mix will not be usable. Once this is in swupd can check for this flag file instead of just guessing the build was good.
Fixes #289 but will need a change in swupd as well.
=> mixin: write flag file for good builds

swupd/create_manifests.go
This patch moves the complicated processing loops out of top-level
functions to make them more readable and thus reduce gocyclo complaints
for this operation.
I'm trying to improve our cyclo score reported here: https://goreportcard.com/report/github.com/clearlinux/mixer-tools
=> swupd: clean up manifest creation

Makefile
=> Create man page directory if it doesn't exist

builder/builder.go, builder/format.go, mixer/cmd/build.go, mixer/cmd/root.go
Whole buncha bug fixes. See corresponding commit messages.
=> [AFB] Fix AFB  bugs

builder/builder.go, builder/bundles.go, builder/docker.go, builder/docker_test.go, builder/format.go, config/config.go, helpers/helpers.go, mixer/cmd/build.go, mixer/cmd/root.go, mixin/build.go, swupd/create_manifests.go, swupd/manifest.go, swupd/manifest_test.go
This PR introduces automatic format-bump support and containerized mixer builds.
=> Add auto format bump support into mixer

builder/builder.go
Run each version back for delta packs in its own thread, and divide the total number of CPUs available and use that in each version thread.
There are cases where only a few files remain to delta, and they take multiple minutes to finish. Each version runs synchronously with many threads, so at the end of a version we have to wait for the long delta to finish before running through another. This changes it so by the end of the run - all the large/slow files are building at the same time, capping it to just one long file run, vs long run * number of versions back.
=> Parallelize version back for deltas

mixin/build.go
=> mixin: increment mixer version when necessary

swupd/delta.go
=> Provide more standard output on bsdiff errors

bat/lib/mixerlib.bash, builder/builder.go, mixer/cmd/root.go
=> Do not hit the network for some commands

builder/docker.go
A couple quality of life changes to docker usage.
=> Docker Improvements

mixer/cmd/repos.go
=> Use cobra for exact args limits

builder/builder.go
=> Fix divide by zero when no previous manifests

swupd/archive.go, swupd/packs.go, validate-swupd.sh
=> Switch to zstd compression in pack creation

builder/builder.go, mixer/cmd/repos.go
=> Add excludepkgs option to repo command

mixer/cmd/repos.go
=> repo: add use-case to exclude long text

builder/bundles.go
Two issues, first is resolved by renaming the error variable to a
goroutine isn't sharing err from outer scope with all other goroutines.
The second issue is resolved by locking concurrent writes on the same
map and using a sync.Map to safely read a map via the Range function.
=> bundles: fix data race in building bundles

mixer/cmd/build.go
=> Don't minver the +10 by default

builder/bundles.go
#113: For a clear linux mix, the os-release file will be updated as follows:
- NAME=_"Clear Linux Mix"_
Eventually this value should be read from user input when #424 is implemented.
- ID=_\<based on above NAME field>_
E.g. **ID=clear-linux-mix**
- VERSION=_"\<mix-ver> (\<upstream-ver>)"_
E.g. **VERSION="10 (24750)"**
- PRETTY_NAME=_"\<NAME> \<mix-ver> (\<upstream-ver)"_
E.g. **PRETTY_NAME="Clear Linux Mix 10 (24750)"**
- VERSION_ID=_\<mix-ver>_
E.g. **VERSION_ID=10**
- BUILD_ID=_\<upstream-ver>_
E.g. **BUILD_ID=24750**
- MIX_UPSTREAM_URL=_"\<upstream-url>"_
This will be a new field in os-release.
E.g.  **MIX_UPSTREAM_URL="https://download.clearlinux.org"**
=> #113 bundles:Update os-release file with mix info

mixer/cmd/root.go
There are a couple mixer commands that don't require network and thus
skip any network check. This behavior is also intended when the
--offline flag is used, but the flag is never checked in that scenario.
This patch unifies builder.Offline (which is set by --offline) and
networkCheck variable to make sure the network check is also skipped if
--offline flag is used.
=> cmd: Respect --offline flag for network check

swupd/create_manifests.go
When a bundle gets deleted, its entry still exists in the previous MoM
but it shouldn't exist in the new MoM. Since the deleted bundle will not
exist in the bundle list anymore, it must be also verified to determined
if an missing entry should be propagated to the new MoM.
=> swupd: Don't add deleted bundles to MoM

swupd/helpers_test.go
Signed-off-by: Otavio Pontes <otavio.pontes@intel.com>
=> helpers_test: Fix checkNotContains warning message

swupd/archive.go, swupd/delta.go, swupd/external.go, swupd/fullchroot.go, swupd/fullfiles.go, swupd/manifest_format.go
=> swupd: add copyright headers to all source files

Makefile.bats, bat/lib/mixerlib.bash, bat/tests/04-create-mix-with-custom-content/run.bats, bat/tests/05-create-mix-with-blended-content/run.bats
Small improvements to battest. See commit message for details.
=> Bat Improvements

bat/lib/mixerlib.bash, bat/tests/06-test-format-bump/run.bats, builder/metadata.go, mixer/cmd/build.go
Implements new format bump process internally in mixer under the format-bum new/old commands.
=> New format bump process

docs/mixer.build.1.rst, docs/mixer.versions.1.rst
Add information about --skip-format-check
=> docs: Add --skip-format-check information

swupd/manifest.go, swupd/rename.go, swupd/rename_test.go
=> Return error instead of panic while generating delta.

README.md
Existing URL is responding with a 404
=> Update mixer documentation link

builder/builder.go, builder/update.go
The latest file in version/formatXX isn't signed by mixer.
Mixer signs the latest file so clients could check the signature of that file too.
Signed-off-by: Ashlesha Atrey ashlesha.atrey@intel.com
=> Signing the latest file in version/formatXX dir

config/config.go
This patch expands mixer config type support to allow int and slice
values to be present in builder.conf. The expandEnv method is now
restricted to string variables and the `config set` command has been
expanded to allow comma separated lists as input for TOML lists.
=> config: Add support for slice and int values

bat/tests/config-conversion/configs/1.2_builder.conf, builder/update.go, config/config.go, config/config_convert.go, swupd/archive_test.go, swupd/cmd/create-fullfiles/main.go, swupd/fullfiles.go, swupd/fullfiles_test.go, swupd/helpers_test.go, swupd/packs_test.go
Allow user to configure compression methods for fullfiles.
=> Selective Compression

builder/bundles.go
Fixes index out of bound error.
=> Fix index out of bound error

builder/bundles.go
Fix rpm filename convention
mixer can now support any format of rpm Name. It uses dnf repoquery to fetch the rpm name.
fixes #648
=> Fix rpm filename convention

builder/bundles.go
=> Make error message consistent

builder/update.go
Add more zero pack logs for debugging in case of missing zero
packs.
=> Add more logs for zero pack creation

builder/update.go
The `err` variable was shared and updated in the zero pack go routine. This could cause race conditions and undesirable results including segmentation fault.
This PR creates a local `err` variable within the zero pack go routine.
=> Remove shared variable in zero pack goroutine

builder/build_validate.go
rpm 4.12 used md5 file hashes by default and rpm 4.14 switched the
default to sha256. As a result, in version 31680 of Clear, rpms started
to use sha256 hashes instead of md5. Since MCA assumes that hash changes
indicate content changes, hash comparisons between md5 and sha256 are
skipped to avoid false positive errors.
=> MCA: Skip hash comparisons between md5 and sha256

builder/bundles.go
In the current mixer version, to improve performance we are not using dnf install to extract the packages.
Hence the database used to create os-packages file is not being populated and thus os-packages file is empty.
Removing functions which initializes the database and creates os-packages
file.
=> Remove functions which creates os-packages file

builder/bundles.go, builder/helpers.go
=> Fix lint errors

.travis.yml
=> Temporarily remove MCA bat due to travis issues

Makefile
=> Makefile: Install linters if not present

bat/tests/upstream-format-bump/run.bats, builder/metadata.go
Fixes #694 
* When crossing an upstream format that deletes a bundle, the downstream mix will now also delete the bundle.
* Updated upstream-format-bump test to validate proper behavior for upstream/local bundle deletion.
=> Remove deleted upstream bundles when crossing upstream format

builder/build_validate.go, builder/bundles.go, builder/update.go, swupd/create_manifests.go, swupd/fullfiles.go, swupd/manifest.go
Currently while catching errors using channels and select
statements, when the error is caught in select statements, it
is not breaking from the outside loop.
The correct approach is to let the existing go routines finish
executing and return one of the errors caught by the error channel.
It should also close the channel in order to stop executing new go
routines.
fixes #673
=> Error Handling on channels

builder/bundles.go
=> Fix lint issues

mixer/cmd/build.go, mixer/cmd/root.go
Fixes #690
* Add root permission check to `mixer build *` commands.
=> build: Add root permission check

builder/bundles.go
Currently, the “os-core” bundle and its “filesystem” package is a hard requirement in Mixer.
In order to enable a minimal mix for 3rd party, “filesystem” package is made optional.
In case the “filesystem” package is found in any of the mix bundles,
then Mixer should install the “filesystem” package first.
If it’s not found in any of the mix bundles, then filesystem is not
installed.
The “os-core” bundle is still a hard requirement in Mixer.
If the "os-release" file is not found, then Mixer creates and injects a default one.
fixes #704
=> Making a minimal mix

builder/bundle_control.go
=> Make bundle messages consistent

builder/bundle_control.go
When resolving the full mix bundle set, the mixbundles file is now
updated once with the finalized set of bundles. Previously, the
mixbundles file was written many times with intermediate results which
scaled poorly when building with many bundles.
Fixes #724
=> Write mixbundles file once for resolved bundle set

bat/tests/content-chroot/run.bats, builder/bundles.go, helpers/helpers.go
When using content chroots, file uid/gid values should be preserved when
copying them to the full chroot.
Fixes #727
=> Preserve file ownership when using content chroots

bat/tests/content-chroot/run.bats, builder/bundles.go, helpers/helpers.go
When calling the copyFileWithFlags function with the preserveSrc flag
set, file permissions must be set after creating the destination file.
This is necessary because umask can prevent newly created files from
acquiring the source file's permissions.
=> Set file perms after creating the dest file

mixer/cmd/build.go
=> MCA: Skip format bump check

builder/bundles.go
When adding special case files to the full chroot, they will create
missing directories in their path with permissions that may conflict
with content that will be added at a later point. By adding special case
files last, they will not create directories with potentially
conflicting permissions.
Fixes #738
=> Install special case files last

swupd/create_manifests.go
improved the performance of processing bundles by parallelizing read includes
and detectManfestChanges operations to scale better.
fixes #725
=> Parallelize process bundles 

builder/bundles.go
In addition to printing a summary of unresolvable package names whenever
DNF fails, also print error messages for any "unknown" DNF error, and
finally print the full stdout/stderr from failed DNF commands for later
inspection.
=> Make sure all DNF errors are printed

builder/bundles.go
Fix lint issue from previous commit
=> Fix lint issue from previous commit

bat/tests/create-mix-with-custom-content/run.bats
Update the version of the helloworld package used in one of the bat
tests.
=> Update package version in bat test

README.md
=> Update README to indicate CI status

bat/tests/no-delta-packs-over-format-bump/run.bats, builder/builder.go, builder/bundles.go, builder/deltapacks.go, builder/metadata.go, builder/update.go, config/config_convert.go, helpers/helpers.go, log/log.go, swupd/create_manifests.go, swupd/delta.go, swupd/fullfiles.go
=> Refactor logging for consistent messages

mixer/cmd/build.go
=> Show upstream-format command in help

log/log.go, swupd/delta.go
Fixes the remaining part of #759
=> Remove delta file in case bspatch test fails

.github/workflows/ci-tests.yml
=> Update to GitHub Actions v2.1.0

swupd/rename.go
Sometimes (like hex coded license files) there's value in not only ignoring digits
for detecting renames, but also ignoring a-f to deal with hex mismatches
=> Add support for hex renames to mixer
