clearlinux/mixer-tools

create-update.sh
To avoid cluttering the workspace directory, archive the swupd log files
in a new "logs" directory within the workspace, separating the logs by
mix version.
=> Archive swupd logs for every mix build

Makefile.am, pack-maker.sh
- Rename pack_maker.sh to pack-maker.sh for consistency with other
scripts
- Add pack-maker.sh to Makefile.am
This change is necessary to allow future scripts to call
mixer-pack-maker.sh without providing a path to the local repo,
which could change from environment to environment.
=> Add pack-maker.sh to install

create-update.sh
Since create-update supports a custom location for the swupd-server
binaries, if that option is passed, it should be propogated to the
pack-maker, which also calls swupd_make_pack.
=> Propogate repodir location to pack maker if set

pack-maker.sh
When REPO_DIR is set, the actual binary might not exist at that location
(e.g. swupd-server might not have been compiled).
Add an additional dependency check for the REPO_DIR location.
=> Check if swupd_make_pack exists under REPO_DIR

build-chroots.sh
The rest of the mixer-tools scripts (excluding the pack makers) already
set this shell option, so add it to the build-chroots script too.
=> build-chroots: fail by default for errors

helpers
Because 'set -e' is enabled for init-mix.sh, the exit status of 'type'
is not checked, so an error raised by 'type' would exit immediately, not
running the $? conditional logic.
To fix, disable 'set -e' for the dependency check function.
=> helpers: fix error handling for dependency checks

helpers
With the current workflow, the "mix-bundles" repo is used for
mix-specific bundle changes, and the "clr-bundles" repo is treated as
read-only.
So in clr-bundles, the CLRVER_mix branches should always point to the
commit tagged with CLRVER. To make this handling more robust, first
verify that CLRVER exists and is a tag. Then create the CLRVER_mix
branch based on CLRVER, or if the branch already exists, reset it
appropriately.
Since this is the best place to detect invalid CLEAR_VERSION numbers
passed in the builder.conf, I've added that error handling too.
=> Improve clr-bundles branch updates

src/builder/builder.go
Starting with swupd-client v3.8.3, the update-ca directory is no longer
created for the build, so the cert copy is failing. Fix the issue by
creating the directory before the copy operation.
=> Ensure update-ca directory is created

src/builder/builder.go
To save time on copying fullfiles, just make a hardlink from the files in
RPMDIR to the REPODIR.
=> Hardlink rpms when calling add-rpms

src/helpers/helpers.go
Only create the file if the HTTP connection succeeds, and in case of
failure later on during download, remove the partial file.
This let the user retries the operation, otherwise the empty/partial
file will prevent the download. One of such cases is forgetting to set
the https_proxy.
=> When HTTP download fails, don't keep the file around

src/builder/builder.go, src/helpers/helpers.go
And also dump the Stderr of the command to os.Stderr. Without a git
failure might not give enough information about what gone wrong,
e.g. when trying to call "git commit" without a user.email configured.
The commit message was changed to include the Clear version from which
the Mix was based off.
=> Merge git helper functions into one

src/builder/builder.go, src/helpers/helpers.go, src/mixer/main.go
Implements Issue https://github.com/clearlinux/mixer-tools/issues/32
Adds new "mixer add-bundles" command to automate the
addition of bundles to the mix-bundles/ directory.
Currently, adding bundles to your mix means copying
them manually from the pulled
clear-bundles/clear-bundles-&lt;VER&gt;/bundles/ dir to your
mix-bundles/ dir. This is a manual process, and thus
following bundle dependencies (i.e., “include
(other-bundle)”) is a manual process.
This new command parses the requested bundle definitions
and recursively copies bundles into your mix dir. Skips
(with warning) by default if present, or overwrites with
optional "-force" flag. Also optionally auto git commits
new bundle addition with "-git" flag.
Example usage:
```
$ mixer add-bundles -help
Mixer 3.1.0
Usage of add-bundles: …
```
=> Add mixer add-bundles command

src/builder/builder.go, src/mixer/main.go
build-image wants a builder.conf file, but the -config option was
missing from this command.
build-image assumed the template file was a hard coded name; added
functionality to pass through with new -template argument.
Signed-off-by: Mark Horn <mark.d.horn@intel.com>
=> Add new args for build-image

src/builder/builder.go, src/helpers/helpers.go
Also change the caller code to show what error happened: useful to
distinguish 404 from timeouts.
Fix the issue of writing invalid files (without error) if the
.clearversion do not exist. The contents would have the actual error
code.
=> helpers: check http.Get status code

src/builder/builder.go, src/mixer/main.go, yum.conf.in
In order to known if there have been format bumps of the
version of ClearLinux this mix is based upon (upstream),
both the source URL and version will be needed.
See https://github.com/clearlinux/mixer-tools/issues/30
Signed-off-by: Mark Horn <mark.d.horn@intel.com>
=> Save Mixer Upstream URL and Version

src/builder/builder.go, src/mixer/main.go
Adds support for an '-all' flag to mixer add-bundles.
This flag takes precedence over the list passed with
the '-bundles' flag, and still supports '-force' and
'-git' options.
Note: this commit also passes the '-q' ('--quiet')
flag to git when making a commit, supressing the
potentially long output.
=> Add -all flag to mixer add-bundles

Makefile.gobuild
When building or testing, the existing GOPATH must be preserved for
dependencies to be found outside the project. This allows "go get" to be
used to download dependencies without mixing them with the project
source.
=> Preserve GOPATH in Makefile

Makefile, mixer/main.go
Update the Makefile to work when we are outside a GOPATH. Note that developers are still encouraged to be inside a GOPATH. The Makefile is mostly intended for package creation.
Fixes #40.
This also fixes the recent regression of "make" not working with release tarballs.
=> Update the Makefile

.travis.yml, Makefile
Make easy to run the same checks as travis.
=> Makefile: add a 'make lint' to run gometalinter.v1

Makefile
Some sequential series of steps are better handled in a long function
than in multiple small functions. Forcing a low number might make
those functions "pass the test" but less readable in the end.
The gocyclo can be an useful tool but it shouldn't be used to enforce
a certain limit.
=> Do not enforce a specific cyclomatic complexity

Makefile
Redundant now that 'make lint' is around. Our integration system
already runs 'make lint', so not necessary to enforce 'make lint' in
all the builds.
=> Remove 'make compliant' target from Makefile

swupd/config.go, swupd/create_manifests.go, swupd/create_manifests_test.go, swupd/helpers_test.go, swupd/manifest.go
* Deduplicate bundle includes list and add test 
* Set deleted file hash to AllZeroHash 
When a file is deleted set its hash to all zeros. Add a test to confirm this.
* Restructure processBundles to perform tasks in correct order 
An added test identified issues with how processBundles was adding, removing, and changing files. Certain steps need to happen to *all* bundles before the next group of steps can be completed. For instance, all manifest.Files manipulation must be done before subtracting included bundles, which in turn must be done before detecting if a file has changed.
=> Write three more tests for manifest creation

swupd/create_manifests.go, swupd/create_manifests_test.go, swupd/filesystem.go, swupd/helpers_test.go, swupd/manifest.go
* Add more tests for manifest creation
Add two more tests for CreateManifests. One to test that the state flag is being set correctly for state files and another to test that empty directories are correctly added to the manifest.
* Fix Manifest.MoM writing
There were several issues with Manifest.MoM writing. The filenames included the "Manifest." prefix and the wrong old version was being used to populate the old bundle manifests, resulting in manifests that would update every other version regardless of changed content. This adds a
test and fixes the bugs.
This PR is against the **swupd** branch. I created the `swupd` label to indicate swupd-server rewrite PRs and issues in the future.
=> Add more tests and fix identified issues

builder/builder.go, helpers/helpers.go, mixer/cmd/build.go
Main changes:
- Rename parameters to reflect better their intention. In particular
"signflag" -> "skipSigning"
- Remove unnecessary Stat check for dir creation: MkdirAll will do
that and not fail if the directory already exists.
- Changed commands to do like the swupd_create_update and their output
the error directly to the os.Stdout/os.Stderr.
- Changed most of file path building to use filepath.Join.
- Inline setVersion, since these two steps make sense at build
update level.
- Only create upstreamver file if we create an upstreamurl file, and do
that before the final publishing step.
- Added comments to clarify some of the steps.
=> builder: clean up BuildUpdate

Makefile, mixer/cmd/build.go, mixer/cmd/root.go, mixer/cmd/rpms.go, mixer/main.go
This command will always output the mixer version, regardless of the
dependencies (so callers don't need to worry about extraneous output
in their scripts).
Also make the error message for failed dependency less redundant: the
error from LookPath already says the name of the program that wasn't
found.
=> mixer --version and mixer --check

swupd/create_manifests.go, swupd/create_manifests_test.go, swupd/manifest.go, swupd/manifest_test.go
Maximize Manifest.full
* When a file exists in one bundle, then is added to another bundle as
well, Manifest.full should report the file version as the most recent
changed version. Add test for this case as well.
Make various performance fixes for manifest creation.
* Added an appendFile helper function to unset the Sorted field.
* Optimize linkPeersAndChange 
Instead of an O(N^2) operation (N^3 counting the calling loop) walk each
manifest file list at the same time for a O(N) operation (N^2 counting
the calling loop). Fold filesAdded() and newDeleted() into
linkPeersAndChange so they can take advantage of the double list walk.
A couple minor test fixes
* Fix misnamed test from "format" to "ghosted"
* Change test error to fatal
This test should be fatal so the f.DeltaPeer.Name is not …
=> Swupd performance + maximize full

swupd/create_manifests.go, swupd/create_manifests_test.go, swupd/helpers_test.go, swupd/manifest.go, swupd/manifest_test.go
When a file is older than the minVersion passed to CreateManifests do
not use the old file in the new update. Instead record the file version
as the current version so that new content is generated (via fullfiles
and packs). Add tests for this functionality.
This PR will have commits from #82 until #82 is merged.
=> Generate new content for files older than minVersion

swupd/create_manifests.go, swupd/create_manifests_test.go, swupd/helpers_test.go, swupd/manifest.go
CreateManifests does a lot of bookkeeping that will be useful for
later steps of BuildUpdate, so make it return all this information.
Changed the MoM struct to contain
- The Manifest itself (that list all the bundles), embedded
- The list of updated bundles and their manifests
- The full manifest
=> swupd: return MoM from CreateManifests

builder/builder.go, builder/stopwatch.go, mixer/cmd/build.go, mixer/cmd/root.go, swupd/cmd/create-pack/main.go, swupd/external.go, swupd/external_test.go, swupd/fullfiles.go, swupd/packs.go
Add a global flag --new-swupd to enable use of the new swupd package.
When using that flag, swupd.CreateFullfiles will be called.
See individual commit messages for the details.
This PR depends on #74.
=> Use new swupd package in mixer

swupd/hash.go, swupd/hash_test.go
Following new functionality is exported:
- Calculate swupd hashes without having a file on the disk
- Calculate swupd hashes without having a the whole data in memory
Exports a type containing exactly the metadata used by the swupd hash.
Doesn't change anything in the Hashval or interning, everything should work as before.
=> Exporting more Hash related functions

Makefile, builder/builder.go, mixer/cmd/root.go
Instead of requiring the swupd-server code to create the "format" and
"swupd-server-src-version" metadata files enable BuildUpdate to do so.
Because the mixer version is now used instead of a swupd-server version
move the Version const to builder.go so it can be accessed trivially.
Update the Makefile parsing to point to builder.go and update the access
method in the top-level mixer/cmd/root.go.
RFC: should we change the name of `swupd-server-src-version` file to `mixer-src-version` or something similar?
=> Write update metadata to output directory

builder/builder.go, mixer/cmd/root.go
Fixes #97
Print the correct error message with the correct flag names
--clear-version or --mix-version is not supplied.
=> Fix error message for mixer init-mix

swupd/files.go, swupd/files_test.go, swupd/filesystem.go, swupd/filesystem_test.go, swupd/fullfiles.go, swupd/fullfiles_test.go, swupd/heuristics.go, swupd/heuristics_test.go, swupd/manifest.go, swupd/manifest_test.go, swupd/packs.go
The flag attributes are already exported, but the constants were not,
so export them. Re-order them in the file to be consistent with the
flag order. Flags are now represented by a single byte.
One option in the future is to map the constants directly to their
real values in the file (e.g. 'F', 'D'), instead of having a new
enumeration starting from zero.
Opted not to do the same with rename (fourth byte) since it is
currently mapped in a different way (boolean), but might make sense to
treat it as a modifier instead (as other extensions might reuse that
byte).
=> swupd: export manifest flag constants

swupd/manifest.go, swupd/manifest_test.go, swupd/packs.go
When parsing a file, fill in the Name field based on the
filename, essentially taking whatever comes after "Manifest.". If
doesn't match, just leave Name empty like before.
Small test added so we can keep track of edge cases in the future.
=> swupd: teach ParseManifestFile to fill in the Name field

swupd/manifest.go, swupd/manifest_test.go
Delta peers are only necessary when the file name is the same, but the
contents have change. Avoid setting every identical delta peer and only
set when the files are not the same.
Also remove unused `unchanged` list in `linkPeersAndChange`
=> Only set delta peers if files are not identical

swupd/fullfiles_test.go
This fixes some TODOs we had in TestCreateFullfiles test.
Add hash verification (to ensure the hash is preserved in the fullfile), add cases for directories and symlinks.
=> Improve CreateFullfiles test

builder/builder.go, helpers/helpers.go, mixer/cmd/root.go
This is a revised version of the mixer init PR. It adds the suggested interface changes to CopyFile proposed by @cmarcelo and adds the builder.conf template creation and rpms directory creation to the new CLI.
=> Create default builder.conf and rpms directories on init-mix.

builder/builder.go, mixer/cmd/build.go, mixer/cmd/bundles.go, mixer/cmd/root.go, mixer/cmd/rpms.go
This patch removes the last occurrences where an error would be handled
by builder itself and cause the program to Exit. Now the error is always
propagated to the caller.
=> builder: propagate error to caller

builder/builder.go, builder/bundleset.go, builder/bundleset_test.go, builder/chroots.go, helpers/helpers.go, helpers/helpers_test.go, mixer/cmd/build.go
This rewrites bundle-chroot-builder.py in Go to be part of Mixer
code. Mixer is the only user of that software, and both Mixer and
b-c-b.py the same configuration file, with overlapping fields.
Main differences from bundle-chroot-builder.py:
- New bundleset type was added, that cares about collecting as much
information as possible from the bundles themselves. This type and
related functions also sets us up for success when upcoming changes
to how bundles are specified happen. There is no assumption all
bundles are in the same directory.
- We are not using m4, instead a bundleset takes care of parsing. If
format of individual bundle files change. The upside is that we can
give nicer error messages, specially for the circular case.
- Read the configuration file directly (with go-ini) to …
=> builder: port chroot building to Go

swupd/helpers_test.go, swupd/packs_test.go
- Add tests for the logic of figuring out which bundles need delta
packs between two versions.
- Add tests for creating zero packs, with data from different sources,
as well as incomplete data (so fallback logic kicks in), validating
the contents of the generated pack.
- Add testFileSystem helper struct, to make filesystem-like operations
in a test directory. By using methods of the struct, we reduce a bit
the noise of passing t and dir around.
=> swupd: add tests for packs

builder/chroots.go
Add one more entry to be skipped. This fixes the scenario of using dnf
by changing yum to be a symlink to it.
=> builder: fix generation of versions file when using dnf

builder/builder.go, builder/chroots.go, mixer/cmd/build.go
This lets override the default choice of packager for performing build
chroots. Makes easy to test dnf with --packager=dnf. The flag is
ignored when not using --new-chroots.
Also prints the actual command line being used.
=> mixer: accept --packager flag when building chroots

swupd-extract/archive.go, swupd-extract/main.go, swupd-extract/state.go
swupd-extract is a program that reads a swupd update repository and
extracts the files for bundles of a specific version. It does a
similar job as "swupd verify --install --no-scripts --no-boot-update".
There is code for maintaining the client state, but at the moment it
only care about zero packs. Verification of the Manifest.MoM signature
is done using "openssl" external program.
It has some niceties when we are extracting Clear Linux content
// List the latest clear linux bundles.
$ sudo swupd-extract clear
// Extracts os-core into "output/" directory.
$ sudo swupd-extract clear os-core
// Extracts editors and all its included bundles into mydir.
$ sudo swupd-extract --output mydir clear/20540 editors
but instead of clear, a proper URL with version can be used instead,
i.e. it is easy …
=> swupd-extract: initial import

builder/builder.go
Fixes #126 
Fixes a bug in AddBundles where it didn't clear out the bundles
slice correctly if 'all' was passed AND a bundle list was passed
in. This case never happened with 'mixer bundle add --all', but
did happen with 'mixer init --all'.
=> Fix add all bundle during init bug

swupd/create_manifests_test.go, swupd/files.go, swupd/helpers_test.go, swupd/packs_test.go, swupd/swupd_test.go
Add testSwupd, in the same spirit of testFileSystem, to make tests less noisy.
Convert two tests to use it, to give some context for reviewing it.
Also import new tests from swupd-server.
Related to #138.
=> swupd: improve test infrastructure and import tests from swupd-server

swupd/create_manifests.go, swupd/delta.go, swupd/delta_test.go, swupd/helpers_test.go, swupd/manifest.go, swupd/packs.go, swupd/packs_test.go
Make pack creation call delta generation, so the delta packs have
deltas inside instead of only fullfiles.
To achieve this, the delta generation was modified in following ways:
- Return a list of all the deltas, not only the failed ones, this is
useful when packing. Otherwise a combination of peeking at DeltaPeer
and the failed list was needed.
- Simplify the goroutine logic: since we have a "home" for all the
error values (in Delta struct), we can just feed all of the deltas
to be processed and wait for the goroutines to finish.
- Instead of calling linkPeerAndChange, call a variant that does not
change the versions, that allows the manifest to be used later on
for the rest of packing.
It is still a TODO to consolidate those two linking functions, or
decide it is not worth. …
=> swupd: Add deltas to the packs

swupd/create_manifests.go, swupd/create_manifests_test.go, swupd/filesystem.go, swupd/helpers_test.go, swupd/manifest.go
Add a file->bundle index file to go in a manufactured
os-core-update-index bundle for faster swupd search operations on
client. Instead of downloading all manifests in the current version the
client can just bundle-add this bundle and use the file as its search
helper.
Because this file is part of a bundle and regular update it will be a
candidate for renames and delta updating. Only present files and
symlinks, not directories or deleted files, are added to this file. The
file contains a tab-separated list of filename to bundlename mappings,
sorted first by filename and secondarily by bundle name.
This manifest has to be processed after all other manifests have been
processed because the "subtracted" file lists have to be complete. This
means we have to post-munge the MoM and full …
=> swupd: Add file index for swupd search

swupd/delta_test.go, swupd/helpers_test.go, swupd/packs.go, swupd/packs_test.go
Import a test and add a simple one.
Fix a difference in behavior with swupd-server: a target might have both a fullfile and a delta to it. Added a TODO note that we may want to drop packing the delta in this case.
Improve information about packs -- now we report what delta was pack for a specific file.
=> Import no-deltas test from swupd-server

swupd/helpers_test.go, swupd/swupd_test.go
Import original test from swupd-server. It performs checks when
creating a new version shuffling some files between bundles and also
create delta packs.
The only difference from original is to not check for Manifest to be
inside the packs anymore, as we are not packing them.
=> swupd: import full-run-delta test

swupd/fullfiles_test.go, swupd/helpers_test.go, swupd/rename_test.go
When fatal is called, it will point to the file and line of the fatal
call, which makes test helpers hide the real place in the test of the
error. By using t.Helper(), the fatal output will skip that function,
and showing the file and line of the caller instead.
This makes errors in the output easier to track down to the actual
test line failing. The patch adds t.Helper() calls to the helpers that
don't have them.
Fixes #144.
=> swupd: use t.Helper() in test helpers

swupd/manifest.go
We need to check that both old and new file are present to link them
when linking files with the same name.
We were not hitting issues because of the earlier check for hashes
matching. If the old file was deleted, the old hash would either be
all zeros (not match) or will be the same hash as another file we
renamed to in the old manifest (unlikely to match this new file, but
possible).
=> swupd: fix typo in linking logic for packs

builder/builder.go, builder/bundleset.go, builder/bundleset_test.go, builder/chroots.go
NOTE: Per @cmarcelo's request, I pulled this out of #137 so that it can be merged sooner. It is exactly the same as that commit.
Refactor bundleSet code to:
1) Loosen definition of bundleSet to simply a set, without
additional constraints. This allows the bundleSet to be built
incrementally, instead of all-at-once, which in turn allows us to
not duplicate bundle parsing that happens elsewhere in the code.
The constraints (completeness and cycle-free), as well as the
computation of the AllPackages field in each bundle, are moved to
a standalone "validateAndFillBundleSet" function.
2) Separate out bundle file parsing into a standalone function,
which allows code reuse elsewhere in the code.
3) Move completeness checking into the sort function, thus
eliminating the need to cycle through the …
=> Refactor bundleset

swupd/create_manifests_test.go, swupd/rename.go
The hashes for these two files should be the hash of the rename-to file.
Add test to verify as well.
=> Rename from/to files should have matching hashes

builder/builder.go, builder/chroots.go, mixer/cmd/build.go, mixer/cmd/rpms.go
>**NOTE**: Per @cmarcelo's request, I pulled this out of #137 so that it can be merged sooner, and so the discussion around deprecation can be had here. 
It is almost exactly the same as the commit in #137, but because it's now on its own (instead of on top of the commit now in #148), there was a small conflict in the section in BuildChroots that #148 also touches. This will likely need to be rebased on top of #148 once it merges.
This commit has three main side effects:
1) The .clearversion, .mixversion, and .clearurl files are no longer
hidden files.
They were likely originally hidden to declutter the workspace, but
they are (for now) files the user needs to edit directly, and thus
should not be hidden.
2) The clearversion and clearurl files has been renamed
upstreamversion and …
=> Rename, cleanup, and remove .mixer directory

swupd/create_manifests.go, swupd/manifest.go
The index manifest must be added to the master manifest list in order to
later be compressed for download by client and so the chroot is cleaned
up during the minimize chroots step.
=> Add index manifest to master manifest list

Makefile
Make go test (make check) report the coverage percentage of the unit
tests that run.
=> Add -cover flag to go test

swupd/create_manifests_test.go, swupd/files.go, swupd/files_test.go, swupd/manifest.go
sameFile checks many things which have yet to be detected on the new
manifest such as the Modifier flag. Because the old manifest will have
this information due to being read directly from a file the new file
would be detected as needing an updated version. Only check the hash and
minversion instead of all file data when deciding whether it is the same
file in relation to an update.
Add a test for a boot file to make sure it stays at the correct version.
=> File did not change if hash and name are the same

builder/builder.go, helpers/helpers.go, mixer/cmd/bundles.go, mixer/cmd/root.go
This PR replaces #107.  I don't want anything to slip past people, so please carefully read the individual commit comments for the impact and side effects of each.
> **NOTE**: Per @cmarcelo's request, I pulled the first two commits out and submitted them as #148 and #149. This PR will be rebased on top of that once it's merged.
This is a fairly major overhaul (I rewrote almost everything in #107 to significantly improve efficiency, take advantage of #102 being merged, and to  account for everyone's feedback), so that's why it's a new PR instead of a force push.
The major differences are:
- Refactored to remove the `stringset` package and type abstraction. The `bundleSet` type is used throughout.
- The `mix-bundles` directory is no longer created **iff** the UseNewChrootBuilder flag …
=> Bundle refactor new

swupd/files.go, swupd/manifest.go
Ran into an issue during testing where a build failed and I had no
context to debug with. Add some meaningful information (file and
manifest name) to GetFlagString and WriteManifest failures.
=> Improve error messages for manifest write failures

swupd/rename.go
In addition to digits strip '.' characters from filepaths for rename
partialNames because dots are common in versioned paths.
This enables renames to be detected against a higher number of files as
their versions change.
=> Strip dot characters from rename filepaths

swupd/rename.go, swupd/rename_test.go
Only support renaming a file to a file since renames are not supported
for the other cases. This is done in trimRenamed by only appending to
the rename list if the file is deleted/ghosted or is a TypeFile. It is
necessary to allow all deleted/ghosted files through because we have
lost the file type association at this point. At least the added list
will only contain files and therefore directories and links will not be
renamed.
Add a TODO to stop removing file type information from deleted files.
=> Only support File->File renames

swupd/create_manifests.go, swupd/create_manifests_test.go, swupd/manifest.go
Generation for os-core-update-index was causing many duplicated files to
be added to Manifest.full for each build because the manifest walk was
done incorrectly. It was adding a file every time there was a file miss
when doing the walk because it was appending every time. This was
converted to a simple binary search from the sort package.
os-core-update-index was also both being copied from the old MoM and
generated and added later. This caused a duplicate entry for
os-core-update-index in the Manifest.MoM for every build after the first
one. Now skip the indexBundle when copying over old manifests.
=> Fix os-core-update-index generation

swupd/config.go, swupd/config_test.go, swupd/testdata/groups.ini
Some bundles have uppercase letters in their names. DO NOT make these
lowercase - this has the result of a manifest not being generated for
them because it cannot find the chroot to walk.
=> Sensitively load groups.ini file

helpers/helpers.go
When RunCommandOutput (or RunCommandSilent) fails, only add the STDOUT
and STDERR to the error string if they have any content (otherwise
omit).
Also add some text without a newline in the end of the string to allow
the underlying error to be printed correctly. If you've seen lines
with ": exit status NNN" this last change will make things looks
better.
In RunCommand, simplify the error message taking in account that the
wrap will append the underlying error when printed.
=> helpers: make failure output concise in Run commands

builder/builder.go, builder/chroots.go, mixer/cmd/build.go
DNF already works in Clear and at the moment Yum is not working, so it
is a good time to stop calling it.
Drop the --packager, if an alternative version of DNF have to be used,
just put it in PATH before the system one.
Fixes #115.
=> chroots: always use dnf

builder/builder.go, helpers/helpers.go, mixer/cmd/bundles.go
Adds new command, 'mixer bundle edit', that allows a user to edit local
and upstream bundle definition files. This command will locate the
bundle (looking first in local-bundles, then in upstream-bundles), and launch
an editor to edit it. If the bundle is only found upstream, the bundle file will
first be copied to your local-bundles directory for editing. If the bundle is
not found anywhere, a blank template is created with the correct name. When the
editor closes, the bundle file is then parsed for validity.
The editor is configured via environment variables. VISUAL takes precedence to
EDITOR. If neither are set, the tool defaults to nano. If nano is not installed,
the tool will skip editing, and act as if '--suppress-editor' had been passed.
Passing '--suppress-editor' will suppress …
=> New Command: Mixer bundle edit

builder/builder.go, mixer/cmd/bundles.go
Removes bundles from your mix by modifying the Mix Bundle List
(stored in the 'mixbundles' file). The Mix Bundle List is parsed, the bundles
are removed, and the resultant list is written back out in sorted order. If
bundles do not exist in the mix, they are skipped.
Passing `--local` will also remove the corresponding bundle definition file from
local-bundles, if it exists. Please note that this is an irrevocable step.
`--mix` defaults to true. Passing `--mix=false` will prevent the bundle from
being removed from your Mix Bundle List. This is useful when used in conjunction
with `--local` to *only* remove a bundle from local-bundles. If the bundle being
removed is an edited version from upstream, the bundle will remain in your mix
and now reference the original upstream version. If the …
=> New Command: mixer bundle remove

builder/builder.go
This timing should be printed to assist in evaluating the move to the
new chroot builder.
=> Add timing information for chroot building step

swupd/create_manifests_test.go, swupd/manifest.go
Unsetting the rename-to file type causes a file with no flags set (e.g.
....).  Do not unset the file type when deprecating a rename-to file,
(e.g. F..r). Only unset the file type when deprecating a rename-from
file (e.g. .d.r).
=> Only unset file type when deprecating rename-from files

builder/builder.go
@cmarcelo found one, and a discussion with me about what's going on found the other.
-----
If you update your upstream version number, the tool is supposed to
automatically pull the new definition files for you. There were two
places where it wasn't currently doing that yet, which is now fixed.
=> Fix upstream bundle cache bug

swupd/rename.go
Constant was added in two different areas of the code, but has the
same purpose. Prefer the one with more descriptive name.
=> swupd: use same constant for minimum size to make delta

swupd/delta_test.go, swupd/packs.go
This is different than the old swupd-server. Added a note to the
imported test.
=> swupd: don't pack fullfiles if delta already available

builder/builder.go, swupd/cmd/create-fullfiles/main.go, swupd/fullfiles.go, swupd/fullfiles_test.go, swupd/helpers_test.go, swupd/packs_test.go
Fix an old TODO, this gives visibility in every build about the
compression algorithms being used.
Note the accounting "gzip" (and not "external-gzip") because at the
moment it is being used for links and directories. It probably should
just migrate to use the external gzip later.
```
Output looks like:
=> CREATE FULLFILES
- Already created: 0
- Not compressed:  0
- Compressed
- external-bzip2       40
- gzip                 389
- external-xz          2520
- external-gzip        953
Total fullfiles: 3902
```
=> swupd: return information about fullfile creation

mixer/cmd/bundles.go
When 'mixer add-bundle' was first introduced, the list of bundles
being added was implemented as a single-argument comma-separated
list. It is more intuitive to specify bundles as separate arguments,
and this is the format all of the new 'mixer bundle ___' commands are
taking. (This also simplifies forthcoming mixer autocomplete code.)
This patch changes 'mixer bundle add' to support this new usage.
To make it more clear how bundles are to be specified, the "Usage"
string of help output has been updated for all commands to comply with
more standard conventions. The output now uses square brackets to
indicate optional elements, ellipses to indicate optional expansion,
and angle brackets to indicate variables as opposed to literal constants.
For example:
`Usage: mixer bundle add <bundle> …
=> Mixer Bundle Add: List bundles as separate args

builder/builder.go, builder/chroots.go, mixer/cmd/build.go
By default, do the same as BCB and use NumCPUs. After this commit our `--new-chroots` should be on par with BCB.
This PR is for the last commit. The others are part of #182.
=> Add `--chroot-workers` to build command

builder/builder.go, mixer/cmd/root.go
And print the versions being used.
Fixes #123. (in combination with #153 that was already merged)
=> mixer: add a default value for mix version in init

.travis.yml, Dockerfile, Makefile, Makefile.bats, bat/lib/mixerlib.bash, bat/tests/01-create-simple-mix/Makefile, bat/tests/01-create-simple-mix/description.txt, bat/tests/01-create-simple-mix/run.bats, bat/tests/02-mix-clear-bundles/Makefile, bat/tests/02-mix-clear-bundles/description.txt, bat/tests/02-mix-clear-bundles/run.bats, bat/tests/03-create-mix-with-unique-bundle/Makefile, bat/tests/03-create-mix-with-unique-bundle/description.txt, bat/tests/03-create-mix-with-unique-bundle/run.bats, bat/tests/04-add-unique-package-to-clear-bundle/Makefile, bat/tests/04-add-unique-package-to-clear-bundle/description.txt, bat/tests/04-add-unique-package-to-clear-bundle/run.bats, bat/tests/05-remove-package-from-clear-bundle/Makefile, bat/tests/05-remove-package-from-clear-bundle/description.txt, bat/tests/05-remove-package-from-clear-bundle/run.bats, bat/tests/06-create-mix-with-swapped-clear-packages/Makefile, bat/tests/06-create-mix-with-swapped-clear-packages/description.txt, bat/tests/06-create-mix-with-swapped-clear-packages/run.bats, bat/tests/07-add-clear-package-to-custom-bundle/Makefile, bat/tests/07-add-clear-package-to-custom-bundle/description.txt, bat/tests/07-add-clear-package-to-custom-bundle/run.bats, bat/tests/08-test-format-bump/Makefile, bat/tests/08-test-format-bump/description.txt, bat/tests/08-test-format-bump/run.bats
Add BAT tests for command-line interface testing. Use --new-swupd option to run with new integrated swupd implementation.
TODO: make them run faster pls
TODO: add `make batcheck` to .travis.yml
Collaboration between @matthewrsj @icarus-sparry and @tmarcu (mostly this guy, he originally wrote the tests)
=> Add BAT tests for UI testing

swupd/rename.go
We want information about the link, not the linked file, when doing a
stat on files in the update. The File.Info field holds FileInfo about
the file, not the linked file.
Doing a 'Stat' instead of an 'Lstat' caused an issue where a link was
changed in an update but the target file was not. The target file
therefore did not exist in the full chroot for that update. Performing a
'Stat' caused a panic because the target file could not be found.
=> Perform Lstat instead of Stat on rename files

yum.conf.in
This helps when doing more than one mix back-to-back or when packages
are installed in more than one bundle.
=> Keep yum cache around when building mixes

builder/builder.go, mixer/cmd/root.go, mixer/cmd/versions.go
Replace the workflow of manually updating the two files to get a new
version.
It does check the upstream format and do not cross format bumps. So it
helps preventing people generating wrong content.
Updates #145.
Updates #59.
=> mixer: add 'update-versions' command

swupd/create_manifests_test.go, swupd/manifest.go
When files are subtracted from the manifest also subtract the size of
the file from manifest.Header.ContentSize. This makes the ContentSize
field only reflect the size of the files listed in the current manifest
and not subtracted files. One can then calculate the complete installed
size of that bundle by adding the ContentSize of all the includes
because there will be no overlap from subtracted files.
=> swupd: Do not track ContentSize for subtracted files

validate-swupd.sh
This script creates builds from $1 to $2 if they exist upstream and
performs an os-install, bundle-add, bundle-remove, verify, and update on
each.
=> Add script used to validate new swupd code

builder/builder.go, builder/bundleset.go, builder/bundleset_test.go, mixer/cmd/bundles.go
New command checks local bundle definition files for validity as a separate step. While
'mixer bundle edit' will automatically validate bundles as you edit them, it can
be useful to manually run this validation step on bundles you have previously
written, or have edited using a different tool. Only local bundle files are
checked; upstream bundles are trusted as valid. Valid bundles yield no output.
Any invalid bundles will yield a non-zero return code.
An optional '--strictness-level' flag allows you to control how strictly bundles
are checked. All levels check basic syntax and structure.
low:   Check file name and bundle Title match and are valid bundle names
med:   All of 'low', plus check Description and Maintainer are non-empty
high:  All of 'med', plus check Status and Capabilities …
=> New Command: mixer bundle validate

Makefile, mixer-completion/cmd/completion.go, mixer-completion/main.go
Please see #77 (as well as the commit message below) for info on why I implemented this as a separate executable, and what the alternatives were.
Please also note that, as addressed in #77, this only implements _basic_ completion, which includes all of mixer's subcommands and their flags (and known valid arguments for some commands, like `mixer bundle list`). More sophisticated completion (e.g., `mixer bundle add ed[TAB] --> mixer bundle add editors`) is also possible, but will be added on a command-by-command basis.
----
This patch introduces a new `mixer-completion` executable that generates `bash`
and `zsh` completion files for `mixer`. The executable is built via `make`, but not
installed via `make install`. Instead, `make install` runs the executable,
which writes the `bash` and …
=> Add mixer bash and zsh completion

validate-swupd.sh
The min version of these validation builds should be the FROM version to
mirror actual build process.
=> Add --min-version to swupd validation script

Makefile, mixer-completion/cmd/completion.go
Adds a '--path' override, allowing you to specify the full path
to where the destination file will be written.
=> Add completion file path override

builder/builder.go, mixer-completion/cmd/completion.go
`LOCAL_BUNDLE_DIR` is a new `builder.conf` field introduced in mixer 4.0. It is included in the auto-generated conf from `mixer init`, and it is referenced in the updated documentation (tbd).
Previously, however, it was marked as a "required" flag in the `ReadBuilderConf` function. This meant that existing users, who did not already have this value, were given an error message saying it was
missing, but no useful information about how to fix this.
This patch provides default fall-back value of the user's `PWD + "/local-bundles"` if the field is missing. If this happens, a warning message is output, informing the user to update their conf.
=>  Add a default value for LOCAL_BUNDLE_DIR

builder/builder.go, mixer-completion/cmd/completion.go, mixer/cmd/root.go
This patch adds a persistent `--offline` flag to the top-level mixer
command, which means every command can pass this flag to make mixer
work offline.
When mixer works offline, it skips caching upstream bundle definition
files. This has the implication that every bundle in the user's mix
must be available in `local-bundles`.
=> Add an "offline" mode for mixer

builder/builder.go, mixer-completion/cmd/completion.go
Fixes a bug in the location for where the Mix Bundle List
(stored in the 'mixbundles' file) is read/write during 'mixer
bundle add' and 'mixer bundle remove' commands.
=> Fix Mix Bundle List file bug

builder/builder.go, builder/bundleset.go, builder/bundleset_test.go, mixer/cmd/bundles.go
Previously, "basic" bundle validation included checking that the
bundle filename (currently used as the "bundle name") matched the
"Title" field in the bundle header (currently not used), and that
the "Title" field itself was valid. This was a step toward future
usage, where mixer will use the header "Title" itself.
This caused mixer to be incompatible with previous versions of CLR,
for which these filename-to-title missmatches were allowed and thus
present.
This patch moves this checking exclusively to "--strict" validation,
and removes bundle content validation from "basic" altogether. Basic
validation now only checks that the bundle filename is valid and that
the bundle contents syntax can be parsed.
=> Mixer bundle basic validation change

Dockerfile, builder/builder.go
A version can be missing if the minversion is newer than the previous
version being checked. This is not an error, but should be printed as a
warning to the user in case this is not expected.
=> build-deltas: Do not fail on missing previous versions.

builder/builder.go
Fixes #213 
------
Previously, repeated calls to `mixer bundle add <bundle>` would yield
the same `Adding bundle <bundle> from <source>` output. Because the
Mix Bundle List is treated as a set, and duplicate bundles are removed,
these redundant additions do not change the resultant list, and are
effectively no-ops.
This patch:
a) Explictly skips the bundles if they already exist.
b) Reports this case to the user
As a result, functionality is equivalent, but the no-op behavior is
more explicit and output is more clear.
=> Update 'mixer bundle add' to skip existing bundles

bat/lib/mixerlib.bash
The builder.conf is created and owned by root, so it must be appended to
as root.
=> bat: write to buildconf as privileged user

bat/lib/mixerlib.bash
Touch mixbundles so it does not get autopopulated by init, and use
os-core in the builder.conf so we do not have to include os-core-update.
=> Updates for new mixer

swupd/create_manifests.go, swupd/files.go, swupd/manifest.go
The 'm' flag is used as a special flag by mixer-integration on the
client side to indicate a manifest record in the Manifest.MoM was
created by a local mix. Allow this flag and just set the rename flag to
renameUnset.
Fail when the old manifest exists but is invalid and cannot be parsed.
This is a clear failure case because the old manifest does exist at that
path and therefore the user expects it to be used.
=> Allow for 'm' flag to be used in rename flag spot, fail on invalid manifests

builder/builder.go, builder/bundleset.go, builder/bundleset_test.go, builder/chroots.go, helpers/helpers.go, swupd/bundleinfo.go, swupd/create_manifests.go, swupd/create_manifests_test.go, swupd/delta_test.go, swupd/filesystem.go, swupd/fullchroot.go, swupd/helpers_test.go, swupd/manifest.go, swupd/packs_test.go, swupd/swupd_test.go, validate-swupd.sh
* Build bundle information using dnf commands
Deprecate use of chroot-building for each individual bundle. This allows
us to scale much easier on machines with limited disk space. Because
chroots are decoupled from manifest creation this also makes it possible
in the future to move to doing bundle builds on distributed machines and
allows our bundle numbers to scale. The bundle file list is stored in a
JSON file that is read later by the manifest creation step.
This leaves a fallback in swupd/fullchroot.go to allow users to add
content to a chroot in order to extend a typical build.
* Overhaul tests to use new bundle creation method
This overhaul leaves several tests using the old method of using chroots
to generate the update to verify we aren't totally deprecating the old
method.
Two …
=> Build bundle information using dnf commands

swupd/bundleinfo.go, swupd/create_manifests.go, swupd/helpers_test.go, swupd/swupd_test.go
Allow a user to add extra files to a bundle by adding a file per line to
`<imageDir>/<version>/<bundleName>-extra-files`. Each file must be an
absolute path. At this point the user must manually create the file in
the full chroot as well.
The workflow for a user adding additional files to a bundle would be
this:
```bash
$ mixer build chroots
$ echo /path/to/bar >> update/image/my-bundle-extra-files
$ mkdir -p update/image/full/path/to
$ cp /local/path/to/bar update/image/full/path/to/bar
$ mixer build update
```
This can definitely be improved in the future but this is a first step
that allows additional content on top of what dnf installs.
In the rare case that a post-install action for dnf install adds a file,
this file would already exist in the full chroot and would not need to
be …
=> Add support for adding extra files to a bundle

builder/chroots.go
Fix a typo that resolved /lib paths to /usr/lib64.
=> Resolve /lib to /usr/lib instead of /usr/lib64

builder/builder.go
Previously, the names of bundles were output differently from one
command to another. Some would insert the bundle name as-is, some would
surround it with single quotes, and some would use double quotes.
This patch normalizes all output (that I could find in builder.conf) to
use the same output format: all now use the %q formatter, which renders
them with double quotes.
=> Normalize bundle name output

bat/lib/mixerlib.bash, bat/tests/01-create-simple-mix/run.bats, bat/tests/02-mix-clear-bundles/run.bats, bat/tests/03-create-mix-with-unique-bundle/run.bats, bat/tests/04-add-unique-package-to-clear-bundle/run.bats, bat/tests/05-remove-package-from-clear-bundle/run.bats, bat/tests/06-create-mix-with-swapped-clear-packages/run.bats, bat/tests/07-add-clear-package-to-custom-bundle/run.bats, builder/builder.go, builder/bundles.go, mixer/cmd/build.go, mixer/cmd/rpms.go, validate-swupd.sh
Recent changes deprecated the use of individual bundle chroots when
building bundle contents and moved away from using yum to using dnf.
Because of this much of our variable and file names and comments were
inconsistent with the implementation.
This includes a change to make 'mixer build chroots' an alias to 'mixer
build bundles' and updates to the bat tests to call the new 'mixer build
bundles' command. This is not a breaking change since 'mixer build
chroots' behaves the way it always has (except internally with the
recent changes mentioned).
=> Convert chroot/yum references to bundles/dnf

builder/builder.go
Recently, code was added to ReadVersions to parse the mixversion
and upstreamversion string values as uint32 values. This patch
adds the same logic to init (the only command that does not
result in a call to ReadVersions), so that the parsed versions
will be consistently available.
=> Parse version numbers on init

builder/bundles.go
Do not just install the AllPackages list to the full chroot, since this
is just the list of all included packages. The DirectPackages need to be
installed instead since this is the fully resolved list for each bundle.
AllPackages do not need to be installed because all bundles are being
installed to the same place.
~~**DO NOT MERGE UNTIL I COMPLETE TESTING**~~
=> Install DirectPackages to full chroot

builder/bundles.go, yum.conf.in
Keeping the cache around has resulted in interesting errors with invalid
bytes being read from the cache and resulting in DNF tracebacks. As a
fix for this tell DNF not to keepcache and manually clear the cache
before doing the full install. This seems to either be a bug with DNF
itself or maybe with the way Clear Linux is doing its packaging (though
this is just a guess).
The error seen is a UnicodeDecodeError from the DNF source code. It is
trying to decode a non-UTF-8 byte as UTF-8:
Traceback (most recent call last):
File "/usr/bin/dnf", line 58, in <module>
main.user_main(sys.argv[1:], exit_code=True)
File "/usr/lib/python3.6/site-packages/dnf/cli/main.py", line 179, in user_main
errcode = main(args)
File "/usr/lib/python3.6/site-packages/dnf/cli/main.py", line 64, in main
return …
=> Clear cache before DNF install to full chroot

builder/builder.go
Previously mixer wrote the mix bundle list as a newline-separated list,
rather than as a newline-delimited list. This made things like "wc -l"
report one fewer than expected, as the final line contained no newline.
This trailing newline does not affect the existing parsing code.
=> Add trailing newline to mixbundles

builder/builder.go, builder/bundleset.go, validate-swupd.sh
This patch adds the capability to add package-scope bundles to your mix
either from upstream `packages` file or from a `local-packages` file in
your mix directory. These files list one package per line like so:
```
helloworld
vim
emacs
```
The bundles created from these packages will be named after the package
itself and will only have that one package defined (plus filesystem as a
hard-coded depencency). The bundle will have no includes. A bundle
definition for the `helloworld` package will look like this:
```
Name: helloworld
Filename: /path/to/{local-packages,packages}
DirectPackages: [helloworld, filesystem]
```
These packages can be added as bundles simply by running
```
mixer bundle add helloworld
```
and mixer will look for the definition in the following order:
1. local-bundles …
=> Process package-scope bundles from package lists

builder/bundles.go, builder/bundleset.go, swupd/bundleinfo.go
When building bundles perform all DNF transactions in bulk. There are
two reasons to do this.
1. DNF is too smart for its own good. It will resolve dependencies
differently depending on the packages listed in the transaction.
Therefore we must perform these transactions with all relevant
packages listed for the bundle being processed.
2. DNF transactions take time. When performing much fewer transactions
in bulk the bundle builder can execute in a shorter time.
Certain manifest validation tools also require a complete dep-solved
list of all packages and included packages for a bundle to validate the
bundle manifest. For this reason use the bundle.AllPackages list and
leave the bundle.DirectPackages list as an informational list of just
the direct packages specified in the bundle …
=> Perform all DNF transactions in bulk

swupd/create_manifests.go, swupd/create_manifests_test.go, swupd/fullchroot.go, swupd/helpers_test.go
This step was completely unnecessary and created empty chroot
directories in the image dir. This was a product of a too-direct port of
the old swupd-server for this specific part of the rewrite. It probably
wasn't even needed in the old swupd-server.
=> Do not init image directories from manifest creation

builder/bundles.go
`mixer build bundles` creates a temp dir to use for one of the dnf
commands. This patch cleans that dir up when mixer is done building the
bundles.
This is really minor, as by default it writes to /tmp, which gets
cleaned up eventually anyway. However, `ioutil.TempDir()` will write to
wherever `$TMPDIR` points, which could be anywhere.
=> Clean up tmp dir after building bundles

builder/bundles.go
Previously, --new-chroots was accidentally using the 'CONTENTURL' value
from builder.conf for both the 'contenturl' and 'versionurl' files.
=> Fix version url bug

swupd/create_manifests.go, swupd/manifest.go
A recent bug in swupd-client prevents users from updating due to a
maximum contensize check that was a couple orders of magnitude off.
These clients are broken and cannot update if they have installed
bundles that violate this maximum.
To allow these broken clients to update temporarily set the maximum
contentsize to the bogus contentsize expected by the client.
Remove this check once a format bump has occurred.
=> Add hack to fix bogus contentsize check in client

builder/builder.go, builder/bundles.go, builder/docker.go, builder/format.go, mixer/cmd/build.go, mixer/cmd/root.go
**DO NOT MERGE YET**
- This has a test command (`mixer build docker [command as args]`) that needs to be removed
- This will currently fail to run unless you've already downloaded the test docker image content and put it in the right directory, as it's not actually being published yet.
The key command here is `RunCommandInContainer(cmd []string) error`
I intend to squash these commits before merging.
------------------
This patch Dockerizes mixer. A new '--native' flag is added that, if
passed, will make mixer run on the host system the way it always did.
This defaults to false.
Before every command runs, if '--native' is false, mixer now pulls an
image file published by upstream that contains the core Clear Linux OS and
mixer toolchain for the version of Clear Linux defined in the …
=> [AFB] Dockerize mixer.

builder/format.go, mixer/cmd/build.go, mixer/cmd/root.go
This PR fixes some issues with the `upstreamversion.bump` file:
- Previously "stage the mix for a bump" command was being called at the start of `mixer build format-old`, but it needs to only happen for format bump builds intended to cross an upstream format boundary. If you're just bumping your mix format, your `upstreamversion` file should remain unchanged.
- Adds a `UnstageMixFromBump` function that cleans up the `.bump` file and reverts the `upstreamversion` file if necessary. This is now called at the end of `mixer build format-new`.
=> [AFB] Format bump update

builder/bundles.go
When building the full chroot DNF lays down some state directories/files
which end up in the Manifest.full later on just by virtue of them being
there. These files should be removed from the chroot when all package
operations are completed.
Also
The fullDir path does not change for each bundle. Move it outside the
bundle install loop so it is not reassigned every iteration.
=>  Remove DNF state files from full chroot

builder/builder.go
The use case for this is when you want to always allow scripted calls to
build delta-packs to create a delta-pack from the min-version, which
might match the current version for a full min-version. This is
conceptually equivalent to finding 0 previous versions. Print the
information and return nil.
=> build delta-packs: do not error when --to matches --from

bat/lib/mixerlib.bash, builder/builder.go, builder/config.go, mixer/cmd/build.go, mixer/cmd/root.go, validate-swupd.sh
Deprecate these flags as the new implementation has been heavily tested and can now be default.
bat tests pass.
=> Deprecate and hide --new-swupd and --new-chroots flags

Dockerfile
This patch updates the Travis Dockerfile to build off the new
clearlinux/mixer-ci image.
Previously, the Dockerfile built off the base clearlinux:latest image,
which meant it spent quite some time (~7 min) just building the Docker
image (swup bundl-add'ing the packages it needed) before it could build
and test mixer. This patch eliminates nearly all of that time, as the
Docker build only needs to download an image and copy the mixer files
over.
=> Update Travis to use clearlinux/mixer-ci

builder/docker.go, builder/docker_test.go
This patch adds an access check on each directory in the config file
before mounting it to the container. This prevents the user from
accidentally (or surreptitiously) granting the container access to
directories they shouldn't.
The config parsing for directory extraction code is also refactored to
provide better results and more accurate error messages.
This patch also adds unit tests for directory access checks, directory extraction,
and mount path list reduction.
For these tests to not fail inside the Docker container on Travis, they
need to not be run as root. This patch thus also creates a non-root user
(but with wheelnopw membership), and runs as this user instead.
=> [AFB] Check access permissions on dirs before mounting

builder/bundles.go
The recent change in 'mixer build bundles' contained a parsing bug that
caused some packages to be dropped. The way 'dnf install' output was
split caused the regex to miss the final line on some bundles. This
patch fixes this bug.
=> Fix parsing bug in 'mixer build bundles'

builder/builder.go, mixer/cmd/rpms.go
The add-repo subcommand adds a remote repo configuration to the DNF conf
defined in the builder.conf. This allows users to configure mixer to use
remote RPM repositories when building mixes instead of being limited to
just local RPMs and upstream Clear Linux RPMs.
This feature is an important pre-requisite for enabling PPA-style repos
on the client side.
=> Add add-repo feature to mixer

builder/builder.go, helpers/helpers.go, mixer/cmd/build.go, mixer/cmd/rpms.go
Previously the code was using ioutils.ReadDir which does a stat call
on every file, but none of the code required the results of the stat
calls, just the names.
In addition programs such as git would like to hold information in the
directories. The usual unix way to do this is to have filenames
beginning with '.', and these are ignored by default by things such as
shell globbing and the ls program.
fixes #269
Signed-off-by: Icarus Sparry <icarus.w.sparry@intel.com>
=> Ignore filenames starting with '.'

builder/builder.go, mixer/cmd/repos.go
'mixer repo set-url' allows the user to set the url of a RPM repo to the
url they provide. This is helpful when users want to build mixes off a
mirror of upstream Clear Linux instead of the CDN when the CDN is slow.
mixer repo set-url clear \<mirror-url\>
=> Add mixer repo set-url capability

swupd/fullfiles.go
Instead of using the same error variable across all workers declare a
new error variable for each goroutine. This prevents race conditions
where multiple routines are using the same error variable to make
decisions and failures are missed.
=> Declare local error for fullfile creation

builder/builder.go
The client needs to download the Manifest.full for mixer-integration to
work and expects a tar to exist.
pls merge and release :(
=> Compress Manifest.full as well

bat/lib/mixerlib.bash, bat/tests/01-bundle-commands/run.bats, bat/tests/02-create-mix-with-upstream-bundles/run.bats, builder/config.go, mixer/cmd/config.go
This patchset is focused on getting batcheck to work with --new-config flag.
Other than allowing the flag to be set for every call of mixer command, this change required setting the properties for LOCAL_BUNDLE_DIR and LOCAL_REPO_DIR in a different way for the TOML config. For old config they were simply appended to the end of the file, but for TOML they need to be on the correct section and with the values in TOML format.
To address that, I included in this patch the config set command. This command looks for a given property in a given section and sets that property to whatever value the user provides. There is no validation at this stage. I believe this command also addresses the request made in #270
=> Config Set and Battest for --new-config

builder/config.go
Noticed this while testing the new config value I added for containerized mixer. @rchiossi just fixed a similar bug (using variable name instead of toml name during config setting) in his #290.
-------------------------
Previously, when a "required" config value was missing, the config
object's variable name was reported, rather than the name actually used
in the `builder.conf` file itself.
This resulted in the following output, for example:
`ERROR: Missing required field in config file: ServerStateDir`
rather than
`ERROR: Missing required field in config file: SERVER_STATE_DIR`
This patch falls back to the variable name if a config field does not
have a "toml" name defined.
=> Report TOML config name for missing config values.

bat/lib/mixerlib.bash
The name used in battests for config set were using the name used in the code for the properties instead of the name found in the config file causing the test to fail.
I forgot to change this after the rework on `config set` to use the name in toml tag.
=> [Bugfix] Use config property name in battest

mixin/helpers.go
If the upstreamversion file exists read the current version from there.
Only read from /usr/lib/os-release if the upstreamversion file does not
exist. The os-release file is modified every time a local mix is
migrated to (version * 1000) so reading from that file every time causes
the mix version to multiply by 1000 every mix build.
Fixes #303
=> mixin: read current version from upstreamversion

docs/tutorials/custom-content-from-chroot.md
Some users are asking for instructions on how to build custom bundles
without having to go through the pain of packaging their content in an
RPM. Provide a tutorial explaining how this can be achieved.
=> Add tutorial for adding custom content from build root

swupd/create_manifests.go, swupd/manifest.go
The compareIncludes() function indicates if two include lists are the
same. On the other hand, the changedIncludes variable indicates if the
list has changed, so it is always the opposite of what is returned by
compareIncludes()nd it must be swapped on assignment.
Also, the comparison using DeepEqual cannot be used to compare the list.
We only care if the include list is still the same, not if the properties
of that include have changes. This problem was never triggered since the\
result of this call was being misused.
=> swupd: fix manifest creation

mixin/build.go, mixin/package.go, mixin/repo.go
Fixes #309
Add the local RPMs before checking if they exist via getPackageRepo. If
the .yum-mix.conf does not exist yet initialize this file so the local
repo is configured.
=> mixin: fix local repo bug

builder/builder.go, builder/format.go, mixer/cmd/build.go, mixer/cmd/root.go
Two top level commands now exist for running format bumps:
- build upstream-format This command builds the necessary builds to
cross a mix over a format bump.
- build format-bump This command builds a bump for downstream users.
=> [AFB] Cleanup and add top level bump commands

builder/config.go, builder/docker.go
This patch fixes a bug with the way mixer determined which fields in `builder.conf` were mountable paths.
Previously, mixer treated every field in `[Builder]` and `[Mixer]` as paths on the filesystem (or paths to files whose parent directories needed to be mounted). Introducing the `DOCKER_IMAGE_PATH` field broke this approach.
This patch introduces a new "mount" tag on the config struct fields that indicates whether a config field represents a mountable path. This has several benefits:
1. It allows us to know definitively which fields we should look at.
1. It allows us to look at the entire `builder.conf`, not just the `[Builder]` and `[Mixer]` sections.
1. It removes the restriction that paths in 'builder.conf' be absolute. This absolute check was mostly a sloppy way of checking if a …
=> [AFB] Fix docker mount path lookup

builder/builder.go
This patch changes the way `SERVER_STATE_DIR` is created if it does not already exist, in order to facilitate mounting the directory inside the Docker container.
By default, `SERVER_STATE_DIR` in `builder.conf` is set to `PWD + "/update"`, a path that typically does not already exist and is created automaticallly the first time mixer builds bundles. Historically, `mixer build bundles` was run as root; now it is run as root within a Docker container. In either case, this `update` directory ends up owned by root.
For security reasons, mixer will not mount to the container any directory to which the caller does not have read/write permissions. This means that on subsequent calls, mixer refuses to mount the `update` directory it just created, as it is owned by root.
This patch resolves this …
=> Create SERVER_STATE_DIR with uid/gid of parent

bat/lib/mixerlib.bash, builder/builder.go, docs/mixer.init.1, docs/mixer.init.1.rst, mixer/cmd/root.go, mixin/helpers.go, mixin/package.go
Fixes #300. This has been asked for by numerous people. Even our own BATS tests were using the hack.
Note: Updated the `mixin` call `b.InitMix` to pass `true` for this variable, so it still ends up with only the `os-core` bundle.
---------------
Previously `mixer init` would add four default bundles to your `mixbundles` list, unless it already existed. This resulted in confusing behavior. Some users resorted to creating an empty `mixbundles` list before running 'mixer init' in order to avoid these bundles. Others had a `mixbundles` list already, but expected the bundles to be added anyway. 
This patch changes the behavior to **always** add the four default bundles, even if the `mixbundles` list already exists, unless a new `--no-default-bundles` flag is passed. This does not affect the …
=> No default bundles

builder/builder.go, builder/bundles.go, config/config.go, helpers/helpers.go, mixer/cmd/build.go, mixer/cmd/bundles.go, mixer/cmd/config.go, mixer/cmd/repos.go, mixer/cmd/root.go, mixer/cmd/rpms.go, mixer/cmd/versions.go, mixin/helpers.go, mixin/main.go, mixin/package.go, mixin/repo.go
This PR is the first part of the config unification patch and includes all the pre-work required to remove the extra config files. With those changes in, the remaining patches can be sent as independent PRs as each one only deals with removing one specific config file (e.g. server.ini). This also is the part that requires the most work rebasing, so once they are in, working on further revisions for the rest should be much easier.
=> config-unify part1: Base changes

builder/builder.go
List the repo title (which is not upper cased) instead of the key 'name'
in the section body. This is important because repo set-url and repo add
operates on the section title not the key name.
Fixes #316 
=> Report repo name title not repo key name

internal/client/state.go, swupd-extract/main.go
The client.State struct is used to download and query manifests and
files from a specific swupd repository (and version). It does support
caching of data.
Besides the expected changes to make it is own package
- Only print "downloading" messages when Verbose is set in the struct
- Allow not passing an expected hash when verifying bundles
- Add a GetMoM function to the client.State
This is still an internal package since I think it needs more
iterations before becoming a public package. That said, the upcoming
swupd-inspector tool was implemented with almost no significant change
to the original code.
=> swupd-extract: move clientState to an internal package

builder/bundles.go, swupd/bundleinfo.go, swupd/create_manifests.go, swupd/filesystem.go, swupd/filesystem_test.go, swupd/manifest.go
Add bundle information files under /usr/share/clear/allbundles to allow
clients to perform future bundle-info operations. Write with 'pretty'
indented JSON so it is grep-able and human-readable in the mean-time.
Users will have to install the os-core-update-index bundle to get this
functionality.
=> os-core-update-index: add bundle metadata files

builder/builder.go, swupd/delta.go, swupd/hash.go, swupd/helpers_test.go, swupd/packs.go, swupd/packs_test.go
~This needs to pass make check, opening PR for early review of this new - albeit naive - first pass at re-implementing and parallelizing our delta pack creation.~
In my testing, building delta packs back from 22460 -> 22530 took about 60 minutes with the original code.
With this patch the time is reduced to 5m30s, but there is 1 missing delta and thus 1 added fullfile:
/usr/share/vim/vim81/lang/menu_ja.euc-jp.vim
=> Parallel delta creation

docs/mixin.1, docs/mixin.1.rst, mixin/package.go
When adding a package provide an optional --bundle flag so users can set
which bundle their package is added to instead of automatically adding
it to a bundle named after the repo the package came from.
=> mixin: add --bundle flag for optional bundle name

builder/builder.go, mixer/cmd/root.go
This is the case for when an OSV *is upstream* and does not have a set
upstreamurl. There is nothing to download and figure out the format range
for since they set the bounds manually, so don't crash on this error unless
it is running in a container non-natively.
=> Fix bug for user who don't have upstreamurl file

Makefile, swupd-inspector/cat.go, swupd-inspector/clean.go, swupd-inspector/diff.go, swupd-inspector/get.go, swupd-inspector/log.go, swupd-inspector/main.go
swupd-inspector contains various commands that help read data of a
swupd repository: download the fullfile for a specific file, see the
Manifest for a specific version, see the differences between two
versions.
The 'diff' subcommand was one of the tools used to evaluate whether
the new swupd implementation was generating correct results compared
with the existing clear implementation.
The clientState struct is almost the same as the one used in
swupd-extract, and given the two use cases, a potential candidate to
move over to swupd package (or at least to an internal package so we
can use without being API). I'm postponing this to when we make
further updates to either of the programs.
Like swupd-extract, it does have a shortcut to handle the main Clear
Linux repository
// Shows the …
=> swupd-inspector: initial import

builder/bundles.go, helpers/helpers.go, swupd/delta.go
Set timeout to 1 minute for bsdiff. The majority of all delta creations
take significantly less than 1 minute to run, which signifies that bsdiff
is working on a delta that may be very large, or very difficult to diff. In
all the cases where bsdiff took multiple minutes to finish, the delta ended
up not being used because it was larger than the compressed fullfile. This
attempts to skip those cases and improve delta creation time.
=> Set timeout on bsdiff delta creation

builder/builder.go, builder/docker.go, builder/format.go, mixer/cmd/build.go
This patch address a bunch of different issues I stumbled upon while trying to test the new format bump feature. This patch makes the feature functional again since it is broken on master.
The first two patches are just minor cleanups. The last 5 fix 5 different crashes.
=> Format Bump general fixes

swupd/heuristics.go, swupd/heuristics_test.go
Remove unused heuristics intended to set flags on manifest file records.
Fixes #345
=> swupd: remove old file heuristics

builder/builder.go, mixer/cmd/build.go, mixin/build.go
This patch adds the --skip-fullfiles options for the 'build' subcommand
of mixer. This command will prevent fullfiles from being generated
during 'build update'. Likewise, the --skip-packs option prevents zero
packs form being generated.
This PR addresses issue #352
=> build: add skip-fullfiles and skip-packs option

swupd/bundleinfo.go, swupd/create_manifests.go, swupd/helpers_test.go
Instead of reading the bundle-extra-files configuration file from the
bundle directory under /image/<ver> (which does not exist until mixer
build bundles is run) read from the persistent mixer workspace. This
means users no longer have to copy these files into place after building
bundles.
Fixes #241 
=> swupd: read *-extra-files from persistent location

bat/lib/mixerlib.bash, bat/tests/06-test-format-bump/run.bats
This patch adds temporary tests for the format bump feature. A permanent
test will require the generation of custom docker images with an updated
build of mixer. Until this tooling is available, this test provides a
minimum integrity check on the feature.
The added test checks the operation of a format bump on a real format
boundary. In addition, it checks the integrity of 4 key values:
- image/LasT_VER should point to the +20 version
- Previous version in +20 MoM should point to +0
- Previous version in +10 MoM should point to +0
- FORMAT property in builder.conf should have the +20 format
=> battest: Add test for format bump

builder/builder.go
Mixer will not work with source RPMs added and crash looking for files
that will not actually be provided. This patch removes them as it parses
the RPM list so only valid, usable RPMs get added to the repo.
=> Remove source RPMs before creating the repo

swupd/manifest.go, swupd/packs.go
Add an additional fileContentInManifest check to pack creation to
exclude full files that are represented in the from manifest even if the
version changed in the to manifest. This allows mixer to exclude
unchanged files from delta packs over minversion bumps.
Before patch, delta packs over a min-version bump (only three files changed):
```
Using 12 workers
=> CREATE DELTA PACKS
Creating delta packs from 10 to 20
Creating delta pack for bundle "bootloader" from 10 to 20
Creating delta pack for bundle "os-core" from 10 to 20
Creating delta pack for bundle "os-core-update-index" from 10 to 20
Creating delta pack for bundle "os-core-update" from 10 to 20
Creating delta pack for bundle "kernel-native" from 10 to 20
Fullfiles in pack: 7 …
```
=> swupd: make slim packs across minversions

mixer/cmd/build.go
MarkDeprecated constructs a deprecation message as follows:
`<flag> has been deprecated, <message>`
So message should not have leading capitalization.
=> builder: fix capitalization of deprecated commands

builder/builder.go, swupd/create_manifests.go, swupd/create_manifests_test.go
Just some low-hanging parallelization fruit.
* Parallelize the manifest initiation step which reads in all file information from the full chroot.
* Parallelize manifest compression step
=> Parallelize parts of swupd manifest creation

bat/lib/mixerlib.bash, bat/tests/01-bundle-commands/Makefile, bat/tests/02-create-mix-with-upstream-bundles/Makefile, bat/tests/03-create-mix-bump-version-add-remove-bundles/Makefile, bat/tests/04-create-mix-with-custom-content/Makefile, bat/tests/05-create-mix-with-blended-content/Makefile, bat/tests/06-test-format-bump/Makefile, bat/tests/06-test-format-bump/run.bats, builder/builder.go, builder/bundles.go, builder/format.go, config/config.go, config/state.go, mixer/cmd/build.go, mixer/cmd/root.go
This patchset adds a couple changes to the config system to allow the TOML config to be used as default. Among this changes are a versioning system and, auto detection of the config format.
This patch also introduces the mixer.state file. Currently it only holds the format variable, which was the last remaining transient variable in builder.conf, but the idea is to concentrate all the other temporary files (e.g. upstreamversion) under this state file.
Note: I'm adding subsections to mixer.state file and I'll update this commit before it is merged. This will also make the batcheck pass (atm It will fail when trying to validate the format).
=> Use New Config as Default

swupd/create_manifests.go, swupd/create_manifests_test.go, swupd/manifest.go, swupd/manifest_test.go
=> swupd: persist deletes over minversions, but not format bumps

bat/tests/06-test-format-bump/run.bats, config/state.go
Instead of always using '1' as the default FORMAT value, check first if
the value was available in a legacy config. If not, try using the system
format instead. If both fail, fallback to the hardcoded value as it was
previously done.
=> state: Better default values for FORMAT

mixer/main.go
The new dnf release *in Clear* now does this by default, so we do not have to load
the nosync library anymore.
=> Remove LD_PRELOAD

mixer/cmd/root.go
The --format flag allows a custom format to be provided to a mix on
initialization
=> cmd: Add --format flag to mixer init

config/config.go
The default value for DOCKER_IMAGE_PATH was only set for the old INI
config. As a result, TOML configs would have an empty path that would
generate an invalid docker command to be issued.
=> config: Add missing default value for docker

mixer/cmd/build.go, mixer/cmd/rpms.go
Mixer does not use the hardlink binary anymore, so these dependency checks can be removed.
=> Remove hardlink dependency check

swupd/bundleinfo.go, swupd/create_manifests.go, swupd/manifest.go
Other packages want to use the IndexBundle const to skip processing this
manifest for some validation cases.
=> swupd: export IndexBundle for external use

swupd/bundleinfo.go, swupd/create_manifests.go, swupd/helpers_test.go, swupd/manifest.go
This is useful for other projects trying to use the *-info file.
=> swupd: export BundleInfo struct

builder/builder.go, mixer/cmd/build.go, mixin/build.go
By default, build bundles removes image/ver and www/ver, so that builds
of the same number start with a clean slate. There are specific use cases
where this is not desirable, and the statedir already has a version folder
populated/mounted which shouldn't be wiped. This allows mixer to write
the full chroot into an actual mounted file system for example that is
attached to update/image/VER/full.
Fixes https://github.com/clearlinux/mixer-tools/issues/376
=> Don't wipe output dirs on build bundles

Makefile, builder/builder.go
This change moves the setting of mixer version string from source code
to a variable defined during compilation. This approach is preferable
because:
1- builder.go does not need to change just to change version.
2- simplifies logic in Makefile, no need to retrieve value from source.
=> Using ldflags for mixer version string

builder/bundles.go
When ranging over the syncmap to add packages to a bundle we were
mistakenly ranging over the entire set of bundles and adding all bundle
packages to the same bundle (nondeterministically, since we were doing
concurrent writes to a syncmap). In reality we just need to range over
the repoPkgMap itself and not load it from the syncmap at all. Do this
operation before even storing it.
BONUS COMMIT :fireworks: 
bundles: remove unneeded map assignment dance
We were assigning a map to a map to assign it to a string slice. Instead
just assign the map keys to the string slice directly.
=> bundles: Fix race condition on map.Range

mixer/cmd/root.go
When running any 'mixer config' sub-command, the config will be parsed
in the command itself, so there is no need to pre-parse them in the pre
execution. Those commands also don't rely on network nor cause any
format conflict, so it is safe to skip all the remaining checks like it
is done for the 'init' command.
=> cmd: Fix double config parsing

builder/builder.go
When running 'mixer init' with the --offline flag, there is no upstream
to fetch the default bundles from, so the mix should be initialized
without the default bundles.
=> builder: No default bundles for offline init

builder/bundles.go, helpers/helpers.go, mixin/helpers.go
In some situations dnf may try to combine files from different
encodings. If the command is not running is a UTF-8 locale, this
combination will be missing a new line, causing and error.
An example of this occurrence is the command `dnf repoquery --quiet -l
systemd ca-certs-static ...` which combines a file list from systemd and
ca-certs-static
This patch enforces UTF-8 locale on every dnf execution.
=> bundles: Enforce UTF-8 when running dnf

swupd/bundleinfo.go
Due to the way that we use repoquery, we are returned files that
may be %ghost files in RPMs. These files may be missing and this
is legal and compliant.
While Clear Linux OS does not use %ghost files in any of the RPMs
created, there is nothing wrong with permitting other vendor RPM
files that may list %ghost files, and mixer should just ignore
these files.
This change does just that: If repoquery returns files that are
not existing in the fullimage, prints a warning and continues with
out dropping the manifest for that bundle.
=> Ignore possible %ghost files in RPM files.

builder/docker.go, mixer/cmd/root.go
When --offline is passed, any command executed should not reach over the
network. This introduces a tricky scenario when it is passed to a build
command with --native=false (default), because the command in the
container will be run with --offline, but the native mixer binary will
reach over the network to pull/update docker containers before executing
in them. This patch also makes that process offline only, attempting to
use a cached docker image so that it can run offline fully, but exits if
none exist.
=> Fix global --offline usage

builder/builder.go, swupd/create_manifests.go, swupd/create_manifests_test.go, swupd/helpers_test.go
This patch fix the error handling issue in manifest creation and change it so the number of worker threads matches the one defined by --bundle-workers option. See commit message for detailed description on the issue.
=> Manifest error

builder/bundles.go
All the values inside buildBundlesConfig are already parsed and
available in the code through builder.Config, so there is no need to
parse them again from the config file.
=> bundles: Remove redundant parsing of config file.

bat/tests/07-config-conversion/Makefile, bat/tests/07-config-conversion/configs/1.0_builder.conf, bat/tests/07-config-conversion/configs/legacy_builder.conf, bat/tests/07-config-conversion/configs/nover_builder.conf, bat/tests/07-config-conversion/description.txt, bat/tests/07-config-conversion/run.bats, config/config.go, config/config_convert.go, mixer/cmd/build.go, mixer/cmd/config.go, mixer/cmd/root.go, mixin/root_cmd.go
This patch introduces automatic config conversion, which will update all users to the latest version of mixer config. With this, we can also get rid of the INI config (we only keep the parser to be able to convert from it).
In order to keep config cleaner, all the conversion code now lives in the new config_convert.go file. This way there is no code referencing the old INI config in config.go anymore, nor any conditional branching to handle different versions of the config. 
I also added bat tests to check for the special conversion cases and to test conversion from all older versions.
=> Config convert

mixer/cmd/root.go
The build image command cannot run in a container because there are no
loopback devices to mount in a container environment. Force running with
native if build image is called.
=> Do not use container for build image

helpers/helpers.go
This reverts commit 9cf854d8d6e45dcb087c0bf4f61bfc633c16e43b.
The reduction to the timeout has caused failures for users on slow
networks, so this must be reverted to the default values.
The reduction to the timeout was added to improve user experience when
connection failed due to a proxy error. It would take mixer too long to
fail and the error message didn't indicate what the problem could be.
The error is now properly indicated, so even if it takes a while for the
error to occur the first time, the user should be able to identify the
problem on the spot.
=> Revert "helpers: Reduce download timeout"

builder/builder.go
When building the upstream URL, if the `b.UpstreamURL` was set do a url
with a subpath included, the subpath was being discarded by
`URL.ResolveReference()`. In order to preserve the subpath in the base,
the provided subpath must be manually added to the base URL object.
=> builder: Fix URL build for base URL with subpath

mixer/cmd/root.go
Format bump check requires fetching format for current upstream which
cannot be done if there is no network available. If `--offline` flag is
provided, this check must be skipped.
=> cmd: Skip format bump check if running offline

builder/bundles.go
While #420 managed to properly differentiate custom mixes from the official ClearLinux release, it didn't preserve the information for the official release itself.
For now, this patch should be reverted and we should work on another revision that works for both use cases.
This reverts commit 302f03a70e78cdfad8ef451b0fbbb1c68dc7525d.
=> Revert "bundles:Update os-release file with mix info (#113)"

builder/bundleset.go, builder/bundleset_test.go
Make package file parsing ignore '#' and anything after that until the
end of the line.  Also trim spaces.
This makes the comment syntax the same as bundle files.
=> builder: Use same commenting rules for package file and bundles

swupd/create_manifests_test.go, swupd/manifest.go
Fixes #455
Minversions should not update deleted files to the minversion as this
may cause swupd to attempt to delete content twice. This exacerbates
issues where a directory (/usr/local/bin) was mistakenly deleted in a
version because it was mistakenly added earlier. Updating the delete to
the minversion then causes the directory to be deleted off the client
system again.
=> swupd: do not update delete versions over minversions

afb.sh, bat/lib/mixerlib.bash, bat/tests/08-manual-format-bump-flow/Makefile, bat/tests/08-manual-format-bump-flow/description.txt, bat/tests/08-manual-format-bump-flow/run.bats
This script is intended as a reference and architecture document for a
new format bump flow. This format bump flow is much simpler than the
original/current flow which requires jumping back and forth between the
+20 and +10 builds to create the updates.
=> AFB: Add afb.sh script to outline format bump steps

builder/builder.go, builder/bundles.go, builder/docker.go, builder/stopwatch.go, config/config.go, config/config_convert.go, config/state.go, helpers/helpers.go, internal/client/state.go, mixer/cmd/root.go, mixin/root_cmd.go, swupd/bundleinfo.go, swupd/cmd/create-fullfiles/main.go, swupd/cmd/create-pack/main.go, swupd/create_manifests.go, swupd/filesystem.go
This PR add fixes and improvements to different scenarios where `Fprint*` is used in the code. Each commit can be viewed as a separate PR since they are handling different issues, but since they are needed together to pass lint testing and they are fairly simple individually, they can be review all at once.
The first 3 commits add proper error handling to different parts of the code. The last commit changes the code to use `log` package to handle error and warning messages.
=> Fprintf combo

afb.sh
The version numbers in /usr/lib/os-release and /usr/share/clear/version
should be identical, so overwrite the latter file with the correct
value.
=> AFB: also update version in /usr/share/clear/version

swupd/create_manifests.go, swupd/format_switch.go, swupd/format_switch_test.go, swupd/manifest.go
The contentsize hack exists to work around a bug in swupd-client
v3.15.3 which was released during format25 in Clear Linux. Because mixer
is maintaining backwards compatibility for old formats we can no longer
remove this hack when a new format bump happens in the OS. Instead we
need to apply this arbitrary maximum whenever mixer is building for the
bad format.
Since the manifest_format file no longer only switches for manifest
templates it was necessary to rename the file and associated _test.go
file to format_switch.go and format_switch_test.go, respectively.
Add testing for this functionality.
=> swupd: add contentsize hack to format switch

docs/mixer.1.rst
Waiting on https://github.com/clearlinux/clr-man-pages/pull/4
=> man-pages: add references to os-format manual

mixer/cmd/root.go
Since mixer.state is the expected and supported way for users to set
the format for their builds do not print a warning when doing so. This
warning was being printed for almost every operation, including adding
and removing bundles from the mix.
=> cmd: do not warn when using format from mixer.state

builder/builder.go
Fixes #323
Provide a better error message when listing repositories. The error now
gives a hint to the user to initialize their workspace before running
the command.
=> builder: improve error message when listing repos

swupd/archive_test.go, swupd/fullchroot_test.go, swupd/fullfiles.go, swupd/fullfiles_test.go, swupd/packs.go, swupd/packs_test.go
Improves test coverage for following files:
* archive.go up to >80%
* manifest_format.go to 100%
* packs.go up to >85%
* fullfiles.go up to >80%
* fullchroot.go add explicit test
=> swupd: increase test coverage

swupd/create_manifests.go, swupd/create_manifests_test.go, swupd/helpers_test.go, swupd/manifest.go
The file was no longer being used due to the actual bundle-info files
being published in the os-core-update-index bundle. Because this file is
very large and requires an update every version remove this file.
This commit also fixes a bug where the os-core-update-index bundle was
being created for every build, regardless of changes. This was not a
visibile bug when the os-core-update-index file itself was being created
because it had changes every time. Now that that file does not change
per release we should not be writing the manifest every time.
Fixes #468
=> swupd: remove os-core-update-index file creation

bat/tests/07-config-conversion/configs/1.0_builder.conf, bat/tests/07-config-conversion/configs/legacy_builder.conf, bat/tests/07-config-conversion/configs/nover_builder.conf, builder/builder.go, builder/init.go, config/config.go, mixer/cmd/root.go, mixin/helpers.go
The existence of local repo and local rpms folder has no impact if they
are not used in the mix. This patch removes the `--local-rpms` flag for
`mixer init` and make it always true. This way both folders are always
created and configured in builder.conf during init.
This patch also update the test cases for config convert to address this
change since.
=> init: Always set localrpms

bat/tests/01-bundle-commands/run.bats, builder/bundle_control.go
Currently, as part of `bundle list`, all the bundle names are read
and validated. As a result, `bundle list` fails if an invalid
bundle exists even if it is not added to the mix. This commit removes
bundle name validation as part of `bundle list` thereby fixing #461.
=> bundles: Ignore name validation for `bundle list`

swupd/delta.go
After much testing of recent Clear Linux OS builds, I have determined that a 1-minute timeout for delta creation is not long enough.
In Clear Linux OS, there are several large (~250MB) files in the 'gcc' package that change on a regular basis (sometimes once a day), and delta creation for these files takes between 5.5 and 6.5 minutes each. The delta sizes are around 9-10MB, significantly smaller than the new compressed fullfile size of 49-55MB.
To accomodate these deltas, the timeout should be at least 7 minutes. For one recent build (26170), one of the delta creations took 6min40sec, approaching 7 minutes. To be safe, I am increasing the timeout to 8 minutes in case the build server is under heavier load.
I did regenerate the deltas that originally prompted adding the 1 minute timeout. …
=> Increase bsdiff delta creation timeout

builder/builder.go, builder/builder_test.go, config/config.go
One may wish to add or edit repos before building any mixes, but the DNF
(.yum-mix.conf) is not available until build-bundles is run.
Fixes #452
=> Create DNF conf as part of mixer init

bat/tests/12-no-state-variables-in-full/Makefile, bat/tests/12-no-state-variables-in-full/description.txt, bat/tests/12-no-state-variables-in-full/run.bats, builder/bundles.go
DNF creates two additional state directories in the full chroot if they missing: `/etc/dnf/` and `/etc/dnf/modules.d`.
Update the DNF state path slice so that the `/etc/dnf` directory tree is removed from the full chroot after full chroot creation. This avoids adding those two directories to Manifest.full.
=> Remove /etc/dnf tree in full chroot

bat/tests/09-build-all-delta-packs/Makefile, bat/tests/09-build-all-delta-packs/description.txt, bat/tests/09-build-all-delta-packs/run.bats, mixer/cmd/build.go
Now the 'mixer build all' command supports the --increment flag. When the
--increment flag is passed to 'mixer build all', the mixversion will be
incremented. Otherwise, the mixversion will remain unchanged. This fixes
an issue where delta packs could not be created after using 'mixer build all'.
Fixes #445
=> build: Add increment flag support to build all

bat/lib/mixerlib.bash, bat/tests/09-no-delta-packs-over-format-bump/Makefile, bat/tests/09-no-delta-packs-over-format-bump/description.txt, bat/tests/09-no-delta-packs-over-format-bump/run.bats, builder/builder.go
Fixes #482
Since clients can't update over format bump boundaries anyways do not
attempt to create delta-packs covering that jump.
Add a bat test to validate.
=>  builder: do not create delta-packs over format bumps

mixin/build.go
The "-purpose any" option is required now under openssl 1.1.
NOTE: needs testing
=> mixin: fix MoM verification with openssl 1.1

mixer/cmd/build.go, mixer/cmd/bundles.go, mixer/cmd/config.go, mixer/cmd/init.go, mixer/cmd/repos.go, mixer/cmd/root.go, mixer/cmd/rpms.go, mixer/cmd/versions.go
This might not look like, but it is part of my offline patch. It was so complicated to track all code paths that I end up cleaning up the root code path on the cli module.
This PR includes a couple cleanups and refactor in `cmd` as well as a major rework of root's preRun function.
=> Cli Rework

afb.sh, bat/lib/mixerlib.bash, bat/tests/bundle-commands/run.bats, builder/bundle_control.go, builder/bundleset.go, docs/mixer.1.rst, docs/mixer.bundle.1, docs/mixer.bundle.1.rst, mixer/cmd/bundles.go, mixin/package.go
`bundle edit` will no longer open the editor. It will just create new bundles or copy existing bundles.
This command will locate the bundle (looking first in local-bundles, then in upstream-bundles).
If the bundle is only found upstream, the bundle file will be copied to the local-bundles directory.
If the bundle is not found anywhere, a blank template will be created with the correct name.
This commit also fixes issue #448 and increases test coverage for `bundle validate`.
=> bundles: Remove editor option for `bundle edit`

builder/bundle_control.go, builder/bundle_control_test.go
* Start to add bundle_control unit tests 
Start to add some unit tests for the bundle_control file. There is much
work to still be done as far as testing goes for these methods.
* builder: read upstream-bundles from mix workspace
Instead of requiring upstream bundles be read from a child directory
under where mixer is currently run read them from underneath the mixer
workspace (builder.Config.Mixer.VersionPath) the same way local-bundles
is handled.
* builder: improve isLocalBundle checks based on testing
Some testcases showed these checks were incomplete and not handling
corner cases. Improve the logic of these checks to comply with the new
tests.
=> Builder tests and improvements based on the tests

bat/tests/bundle-commands/run.bats, builder/bundle_control.go
`bundle add` will now add valid bundles and skip only the invalid ones,
thereby fixing issue #489.
=> bundles: Add valid bundles and skip invalid ones

bat/tests/mixin-repo-commands/Makefile, bat/tests/mixin-repo-commands/description.txt, bat/tests/mixin-repo-commands/run.bats, mixin/repo.go
The clear repo is mandatory for mixin. This change prevents mixin from
removing the clear repo.
Fixes #326
=> mixin: prevent removal of clear repo

swupd/create_manifests.go, swupd/manifest.go, swupd/packs.go
When a bundle is updated to only modify which bundles are included, an
iterative manifest can be generated with 0 files. This change adds a
type field to the Manifest struct to determine when an iterative
manifest is used and allows the creation of iterative manifests with
a 0 file count.
Fixes #516
=> Enable iterative manifests with 0 file count

swupd/create_manifests.go, swupd/create_manifests_test.go
During a minversion update, iterative manifests older than the new
minversion were leaked into the new MoM. Also, format bumps perform
minversion updates, so iterative manifests from an old format could
leak into new formats. This change prevents forwarding iterative
manifests with versions older than the minversion into the new MoM.
Fixes #523
=> create_manifests: Don't leak iterative manifests on minversions

builder/bundleset.go, builder/bundleset_test.go, swupd/bundleinfo.go, swupd/create_manifests.go, swupd/files.go, swupd/filesystem.go, swupd/format_switch.go, swupd/format_switch_test.go, swupd/helpers_test.go
From format 27 onwards, Mixer will recognize bundles with "[Status] : Experimental"
as experimental bundles and mark their status flag as "e" in the Manifest.MoM.
i.e. These bundles will include an "e" in the 2nd position of the manifest flags,
as shown here:
Me.. 4b91c3122e7e32f1e3edb597c6f89ff32cfffd977afb5e5 10 some-bundle
Fixes #497
=> builder: Experimental bundles

mixer/cmd/root.go
Earlier the new-swupd and new-config flags were incorrectly marked for
deprecation. After correctly deprecating these flags, they are no longer
present in the help message and print a deprecation message when used.
=> Deprecate new-swupd and new-config flags

builder/format.go, builder/metadata.go, mixer/cmd/init.go
Those 3 patches fix code patches where `--offline` was ignored. They are required for downstream mixes to perform a manual format bump.
=> Offline fix

bat/tests/bundle-commands/run.bats
Version 27310 of clearlinux included os-core-webproxy as dependency of
os-core-update. This adds one extra bundle to the default bundle list.
Since bundle tests will count the number of lines in the output for
validation, this extra default bundle must be accounted for.
=> bat: Fix bundle test

bat/lib/mixerlib.bash, mixer/cmd/init.go, mixin/build.go, mixin/helpers.go, mixin/package.go, swupd-extract/main.go
Use cdn instead of download.clearlinux.org as the standard upstream URL,
because it's more reliable. Other usages of download.clearlinux.org were
also changed with the exception of version number downloads. Downloading
version numbers from download.clearlinux.org is still preferred because
we don't need to be concerned with caching.
Signed-off-by: Otavio Pontes <otavio.pontes@intel.com>
=> Use cdn to download content on mixer

bat/lib/mixerlib.bash, builder/repo_control.go
Since the default Clear repo mirror changed to the cdn, dnf timeouts
occur more frequently. Increasing the timeout to 45 seconds from the
default timeout of 30 seconds.
=> Increment Clear repo default timeout

mixer/cmd/build.go
The clean flag for the mixer build all command was not exposed to users
to change from the default value. Now the clean flag can be set for the
mixer build all command.
=> Add clean flag to mixer build all command

builder/builder.go, builder/bundles.go, mixer/cmd/build.go, mixin/build.go
Download failures can occur when downloading large sets of RPMs from a
server with a poor connection. This change adds retry functionality to
attempt RPM downloads multiple times.
Fixes: #531
=> builder: Retry RPM downloads for build bundles

bat/lib/mixerlib.bash, bat/tests/build-delta-manifests/Makefile, bat/tests/build-delta-manifests/description.txt, bat/tests/build-delta-manifests/run.bats, bat/tests/no-delta-manifests-over-format-bump/Makefile, bat/tests/no-delta-manifests-over-format-bump/description.txt, bat/tests/no-delta-manifests-over-format-bump/run.bats, builder/builder.go, docs/mixer.build.1, docs/mixer.build.1.rst, mixer/cmd/build.go, swupd/delta.go
swupd-server used to support building bsdiff based deltas of manifest
files. This change adds that ability back for bundle manifests with
the 'mixer build delta-manifests' command.
=> Enable create Manifest deltas in mixer

bat/tests/bundle-commands/run.bats
The bundle validation count only needs to account for the bundles that
have been directly added to the mix. With the fragmentation of the
default bundles into smaller bundles that are used as includes, the test
must ignore the included bundles and just count the ones that were
directly added.
=> bat: Fix bundle count

builder/stopwatch.go
Likely a typo when converting to the logger interface. Stops printing
a memory address of the writer given to the stopWatch and just print a
newline.
=> builder: fix spurious print in stopWatch

swupd-inspector/get.go
Fixes log and get.  In these we want to loop at the actual Manifests,
to peek at the entire file list of each.
=> swupd-inspector: ignore "iterative manifests" when visiting all files

bat/tests/config-conversion/configs/1.1_builder.conf, bat/tests/customize-os-release/Makefile, bat/tests/customize-os-release/description.txt, bat/tests/customize-os-release/files/my-builder.conf, bat/tests/customize-os-release/files/my-os-release, bat/tests/customize-os-release/run.bats, builder/bundles.go, config/config.go, config/config_convert.go
New [Os] section is added in builder.conf file to support
OS identification modification such as NAME, VERSION, ID,
ID_LIKE, PRETTY_NAME, ANSI_COLOR, HOME_URL, SUPPORT_URL,
BUG_REPORT_URL and PRIVACY_POLICY_URL for downstream Clear Linux
build.
This section NOT supporting VERSION_ID since it has been used by
Mixer for mixversion.
Example to modify os-release file:
Change the NAME, PRETTY_NAME and PRIVACY_POLICY_URL
[Os]
NAME = "Clear-Linux-A"
PRETTY_NAME = "A Clear Linux OS"
PRIVACY_POLICY_URL = ""
Example to keep value based on default os-release file:
[Os]
ANSI_COLOR = "<NoChange>"
HOME_URL = "<NoChange>"
SUPPORT_URL = "<NoChange>"
BUG_REPORT_URL = "<NoChange>"
Signed-off-by: sweeaun <swee.aun.khor@intel.com>
=> config: Allow OS identification customization #560

mixin/build.go
If custom bundle name matches upstream bundle name, use only custom bundle manifest in MoM.
Otherwise swupd picks up first manifest from MoM (upstream) and fails to validate manifest of custom bundle.
This fixes #566 and allows mixin customisation of upstream bundles
=> Do not duplicate manifests

docs/mixer.init.1.rst, mixer/cmd/init.go
The `--clear-version` flag in mixer init accepts a string as parameter
to allow the user to set it to `latest`, which will auto fetch the
upstream version. For all other cases, this flag must be provided an
integer number. This patch clarifies the valid values for this flag both
in the error message and in the help description.
=> cmd: Improve error message for invalid upstream

builder/builder.go, builder/update.go, swupd/delta.go, swupd/hash.go, swupd/helpers_test.go, swupd/packs.go, swupd/packs_test.go
Solves various race conditions that were identified by building mixer with the -race flag.
The 2nd, 3rd, and 4th commits address issues with `mixer build delta-packs --previous-versions`
=> Fix various race conditions

bat/tests/build-validate/run.bats, builder/build_validate.go
I found additional special case errors for MCA:
1. When a bundle has no packages, MCA should not call dnf without any packages in its argument list.
2. /usr/lib/os-release can be modified by both Mixer and the filesystem package. When Mixer and the filesystem package modified this file, MCA would generate an invalid special case error. This PR reworks how MCA handles /usr/lib/os-release so that an error is not generated when both Mixer and the filesystem package modify the file.
=> Mca bugfixes

builder/update.go
A large number of compression goroutines can cause the system to reach
the open file limit. This change sets an upper bound on the number of
goroutines that can be generated.
=> update.go: Limit number of compression goroutines

builder/builder.go
If publishing an update, also update the www/latest_version.  This is
useful for various consumers of swupd data: swupd-client can easily
discover the latest version (and not only the latest version in a
given format); swupd-inspector and swupd-extract will be able to
automatically figure the latest version of a mix given the update URL.
If --no-publish is used, the file will not be updated like the other
related files.  Clear Linux itself uses that so it can decide later on
whether to publish or not an update to the end users.
Related to #467.  With latest_version is possible to peek at
www/<latest_version>/format and figure its format.
=> builder: create a www/latest_version file

bat/tests/contentsize-check/Makefile, bat/tests/contentsize-check/description.txt, bat/tests/contentsize-check/run.bats, swupd/manifest.go
Directories can be installed with inconsistent sizes. To make mixes
reproducible, the size of directories is omitted from the contentsize
calculation.
Fixes #568 
=> swupd: Remove directories from contentsize calculation

afb.sh, bat/tests/manual-upstream-format-bump-flow/Makefile, bat/tests/manual-upstream-format-bump-flow/description.txt, bat/tests/manual-upstream-format-bump-flow/run.bats, builder/metadata.go, mixer/cmd/build.go, mixer/cmd/versions.go
When doing manual format bumps, the upstream version for +20 needs to be
updated to the upstream version in the new format, but since the format
differs, the build will fail.
This PR adds a new flag to `mixer versions update` and to `mixer build`
subcommands that allows the check this check to be skipped.
=> cmd: skip format bump check

builder/builder.go, config/config_convert.go, config/state.go, mixer/cmd/config.go, mixer/cmd/init.go
MixState needs to know the server state dir in order to find the value
for previous version since its path will not always be relative to the
execution folder.
With this patch, MixState is always loaded after MixConfig. Since the
conversion of older formats of MixConfig account for format transfer,
changing the order does not prevent the format value to be properly
moved to the state file.
=> config: Use server state dir when loading MixState

bat/tests/build-validate/run.bats, builder/build_validate.go, builder/bundles.go, builder/repo_control.go, docs/mixer.build.1, docs/mixer.build.1.rst, mixer/cmd/build.go
Problem:
In some cases (downstream mix with custom content) the `from` and `to` mix versions require different repo settings in the dnf conf file to download packages correctly. This makes it difficult for MCA to consume a single config file when downloading packages for both mix versions.
Approach:
Add arguments that override repo/baseurl settings in a temporary dnf config file for that will be used only when downloading packages for the `from` or `to` mixes.
If this approach is acceptable, I will update with tests
=> MCA: Support repo/baseurl overrides for from and to versions

bat/tests/build-validate/run.bats, builder/build_validate.go
This PR makes the following changes:
1. Sort bundles when printing statistics
2. Add colons to added/deleted packages when printing bundle statistics.
3. Add space between '|' character and bundle name
=> MCA Statistics Reporting Updates

builder/build_validate.go, swupd/bundleinfo.go, swupd/create_manifests.go, swupd/filesystem.go, swupd/manifest.go
This PR makes the following changes:
* Serialize MCA package downloads:
* There was a race condition where packages could be queried by `rpm` before the download finished. Serializing this section does not significantly impact performance.
* Use recursive includes for file/pkg subtraction:
* There were cases when MCA would miss files/pkgs that should have been subtracted. This issue is resolved by checking each of the bundles from the recursive includes list for files/pkgs to subtract. 
* Use `resolveFileName` function to manage symlinks used by Clear Linux packages.
* Re-use existing function to remove duplicated code.
* Skip files with blacklisted characters:
* Mixer does not create entries for files that have names with blacklisted characters (;&|*`/<>\"'). Now, MCA ignores blacklisted …
=> MCA Bug Fixes

builder/bundle_control.go, builder/bundleset.go, builder/bundleset_test.go, swupd/bundleinfo.go, swupd/create_manifests_test.go, swupd/format_switch.go, swupd/format_switch_test.go, swupd/helpers_test.go, swupd/manifest.go, swupd/manifest_test.go
An optional bundle is similar to the required bundles (included
bundles) but have a couple of differences.
- Optional bundles will be installed by default when the main
bundle that includes them is installed.
- Users will have the option to skip the installation of Optional
bundles by using the flag --skip-optional/-o with bundle-add.
- Optional bundles can be removed from the system even if the
main bundle that installed them is still in the system.
From the perspective of Mixer a bundle will be considered as
optional whenever it is marked as optional in the bundle spec
file. E.g. optional(lib-openssl). And it should be added as such
in the bundle's manifest.
Signed-off-by: Castulo Martinez <castulo.martinez@intel.com>
=> Support "optional" bundles in manifests

builder/bundles.go, mixer/cmd/build.go, swupd/bundleinfo.go, swupd/create_manifests.go, swupd/delta_test.go, swupd/format_switch.go, swupd/format_switch_test.go, swupd/manifest.go
This PR deletes the index manifest when transitioning from format 28 -> 29. Since this manifest is directly injected into the mix, it cannot follow the typical bundle deletion workflow. As a result, there are some cases where the deletion will not be smooth:
1. Upstream mixes must create an empty bundle chroot during a format bump from 28 -> 29 for the os-core-update-index manifest to delete it.
2. Downstream mixes ahead of upstream Clear's format (format 28) will miss the index manifest deletion.
3. Downstream mixes that do not upgrade Mixer to include this change when advancing their mix to format 29 will miss the index manifest deletion.
If a mix does not successfully delete the index manifest, the following will happen:
1. The os-core-update-index manifest will be removed from the …
=> Delete index manifest

builder/build_validate.go, swupd/filesystem.go
Previously, MCA parsed rpm output with commas which is a valid file
character. Now, rpm output is parsed with \a which are
blacklisted file characters for Mixer.
=> MCA: Parse rpm output with \a characters

swupd/bundleinfo.go, swupd/create_manifests.go, swupd/manifest.go
When creating file records for a manifest, skipping files from the
bundle info file list that exist in one of the manifest's nested
includes removes the need for manifest file subtraction. This improves
performance because it reduces the number of unnecessary file hash
calculations and removes the need for bundle manifest file subtraction.
=> swupd: Skip included files when creating file records

bat/tests/build-multiple-delta-packs/Makefile, bat/tests/build-multiple-delta-packs/description.txt, bat/tests/build-multiple-delta-packs/run.bats
Added testcase for generating deltapacks with missing files for
different versions. If file is missing, delta pack for that
bundle should be ignored as delta pack generation is optional.
=> Added test case for generating delta packs with missing files

swupd-extract/main.go
We are using purpose any for signature verification on swupd and mixin. Updating
swupd-extract to use the same.
Signed-off-by: Otavio Pontes <otavio.pontes@intel.com>
=> swupd-extract: Use correct purpose on manifest signature verification

.travis.yml, Dockerfile
This PR breaks bat tests into individual test runs within travis
infrastructure. This is a workaround the current test failures on travis
due to infrastructure limitations and allow us to reset a single test in
the case of a failure.
This patch also disables create-mix-bump-version-add-remove-bundles test
since it is unable to complete in travis infra.
=> travis: Parallelize bat tests

builder/build_validate.go, builder/update.go, swupd-inspector/get.go, swupd/create_manifests.go, swupd/create_manifests_test.go, swupd/delta_test.go, swupd/files.go, swupd/format_switch.go, swupd/format_switch_test.go, swupd/helpers_test.go, swupd/manifest.go, swupd/packs.go, swupd/packs_test.go, swupd/swupd_test.go
Reverting all patches that added Iterative and Delta manifests in mixer.
Only Iterative Manifest leftover is the ability to parse MoM with Iterative manifests. This is necessary because when we build an update we need to parse previous manifest, that may have an Iterative Manifest.
Also added code to prevent mixer to carry Iterative manifests to a new MoM when an update is built.
=> Manifests: Remove Iterative and Delta Manifests

builder/builder.go
InitMix() calls AddBundles() and getUpstreamBundles().
AddBundles() already calls getUpstreamBundles().
So remove the redundant function call in InitMix().
=> Remove redundant getUpstreamBundles() call

builder/bundles.go, builder/bundleset.go, mixer/cmd/build.go
Extracting rpm using rpm2archive and tar is faster than dnf and will
improve performance significantly.
Fixes #631 
=> Extract Rpms using rpm2archive and tar instead of dnf

bat/tests/config-conversion/configs/1.2_builder.conf, builder/builder.go, builder/builder_test.go, builder/bundle_control.go, builder/bundle_control_test.go, config/config.go, mixer/cmd/init.go
Currently, the bundle defintions are downloaded from the default
clr-bundles repo https://github.com/clearlinux/clr-bundles/archive/.
The user can now specify a different upstream bundles url using a mixer init flag or mixer
config parameter.
E.g. mixer init --upstream-bundles-url=https://github.com/reaganlo/clr-bundles/archive/
E.g. mixer config set Swupd.UPSTREAM_BUNDLES_URL https://github.com/reaganlo/clr-bundles/archive/
Since there is a tight coupling between the --upstream-version and bundles
repo, the user should ensure that the bundles repo has the same structure as the
clr-bundles repo and the tar.gz files should be named after an upstream
version. i.e. If the mix is based on an upstream-version 31300, the bundles repo
should have a file 31300.tar.gz
Fixes clearlinux#614
Note: …
=> Introduces option for upstream bundles url

builder/deltapacks.go, builder/update.go, swupd/cmd/create-pack/main.go, swupd/packs.go, swupd/packs_test.go
Create zero packs in parallel
Fixes #629
Decided not to reuse the parallel code of delta packs for zero packs because there were certain differences such as 1) For zero packs, stop processing in case of error. For delta packs continue processing even in case of error because delta packs are optional. 2) The report and print statements are different. etc.
Decided to reuse the delta-workers as the the numWorker for zero packs. This is because mixer is already overloaded with too many numWorker flags such as delta-workers, bundle-workers and fullfile-workers. Did not find the need to introduce another new one. Also, technically a zero pack is a delta pack.
=> Create zero packs in parallel

builder/bundles.go
Currently, the error message for rpm2archive displays incorrect rpm.
This PR displays the correct rpm in the error message.
=> Fix logs for rpm2archive

builder/bundles.go
Fix to fail Early if rpm not found
if rpm is not found in the cache dir of clear-*, we can fail early
instead of failing during extraction.
=> Fix to fail Early if rpm not found

builder/build_validate.go, builder/bundles.go, builder/bundleset.go
For current version of mixer, if dependencies are not resolved, it
continues with installing other bundles.The correct behavior should be to fail at this point .
While resolving packages, if dependencies are not resolved then we stop the processing 
and return error.
fixes #663
=> Stop processing bundles if missing dependencies

builder/repo_control.go, mixer/cmd/repos.go, mixin/repo.go
Currently, `mixer repo remove` displays incorrect messages if repo does not exist.
This fix displays the correct message.
=> repo: Fix message while removing repo

builder/builder.go, builder/bundles.go, builder/bundleset.go, builder/repo_control.go, mixer/cmd/repos.go
Currently mixer allows users to set multiple repos using 'mixer repo set' commands and name them anyhow.
But the code within the mixer is tightly coupled to having only two repos - "clear" and "local".
This inconsistency is fixed.
fixes #654
=> Setting multiple repos in mixer

builder/bundles.go, mixer/cmd/repos.go
Keep repo messages and help consistent.
Also, call ListRepos() earlier on during build bundles, to suggest
context.
=> Keep repo messages and help consistent

builder/build_validate.go, builder/bundles.go, builder/repo_control.go
* MCA: Instead of querying packages downloaded by `dnf install`, the packages are resolved and queried with `rpm`. When the packages are in repos on the local system, the query operation is much faster.
* MCA: Added support to resolve packages that do not follow NVRA name format.
* MCA: Suppress verbose Mixer output
* Return more package metadata during `resolvePackages`
Based on local MCA testing, with all bundles and package repositories on the local system the execution time improved from 106min 11sec -> 15min 11sec.
=> MCA refactor pkg queries

bat/tests/build-validate/run.bats
Don't check this error so that it does not need to be updated when MCA changes.
=> bat: Remove MCA error string check

bat/tests/create-mix-with-custom-content/Makefile, bat/tests/create-mix-with-custom-content/run.bats, builder/bundles.go, mixer/cmd/repos.go
Currently, for repos with "file" baseurl scheme, mixer expects the
rpms to be directly within the baseurl path.
But it is possible that rpms can be in sub directories within the repo baseurl.
In order to handle this, if an rpm is not found directly within the repo baseurl,
run repoquery to determine the actual location of the rpm.
This is expensive and it is recommended that rpms are stored directly
within the repo baseurl.
Includes a bat test.
Fixes #674
=> repo: Handle rpms in repo sub directories

builder/bundles.go, builder/repo_control.go
repo: Improve performance for multiple repo subdir
If an rpm is not found in the assumed cache dir of its repo, update the
repo cache dir list based on the location of the rpm.
This is an attempt to improve performance in case the rpms are not
stored directly within the repo baseurl.
=> repo: Improve performance for multiple repo subdir

swupd/manifest.go, swupd/manifest_test.go
Fixes #684 
* Prevent newly generated manifests from dropping previously deleted file entries when the new manifest has less file entries than the previous manifest.
* Add test case to verify that previously deleted file entries are retained.
=> swupd: Retain previously deleted file entries

builder/repo_control.go, docs/mixer.repo.1, docs/mixer.repo.1.rst, mixer/cmd/repos.go, mixin/repo.go
Fixes #691 
* Add set-priority to repo command: `mixer repo set-priority <repo> <priority>`
* Increase code re-use for repo commands
=> Add set-priority to repo command

builder/bundles.go
while build bundles, if build fails to resolve packages, improve error
message by printing which packages were not found.
fixes #697
=> Improve Error Message for unresolve packages

bat/tests/customize-os-release/files/my-os-release, bat/tests/customize-os-release/run.bats, builder/bundles.go
BUILD_ID field in os-release file specifies the upstream Clear
Linux version from which the mix is being created.
If upstream Clear Linux is not found, BUILD_ID is empty.
fixes #706
=> Add BUILD_ID field in os-release file

builder/bundles.go
If mix is minimal mix with empty os-core, directory path for
os-release file does not exist.
Create a directory path before updating the os-release file
=> Create Dir path for OS-Release file

bat/tests/clean-rebuild/description.txt, bat/tests/clean-rebuild/run.bats, builder/builder.go, mixer/cmd/build.go, mixin/build.go
Existing image and output directories for the current mix version will
be removed when building a mix. This prevents mixer from building on top
of directories contaminated by a prior mix.
Fixes #669
=> Always clean mix workspace before building bundles

builder/bundle_control.go, docs/mixer.bundle.1, docs/mixer.bundle.1.rst, mixer/cmd/bundles.go, mixin/package.go
mixer bundle create command with local flag can be used
to create an empty bundle file with just the definition
header information.
fixes #713
=> Add --local flag in mixer bundle create command

builder/deltapacks.go
Fixes #551
Delta packs are generated concurrently, so their results output must be
printed once to prevent interleaved results.
=> Print delta pack results together

builder/bundles.go, builder/bundleset.go
Currently, build bundles generates an error if one of the mix bundles
has only an 'also-add()' entry in its definition.
Instead, build bundles should not error out and must process such
bundles.
Fixes #718
=> Handle optional bundles

.travis.yml, bat/tests/export-flag/Makefile, bat/tests/export-flag/description.txt, bat/tests/export-flag/run.bats, builder/bundle_control.go, builder/bundles.go, builder/bundles_test.go, builder/bundleset.go, mixin/build.go, swupd-inspector/diff.go, swupd/bundleinfo.go, swupd/files.go, swupd/files_test.go, swupd/filesystem.go, swupd/helpers_test.go, swupd/manifest.go, swupd/manifest_test.go, swupd/rename.go
- Change RenameFlag to MiscFlag
Change RenameFlag to MiscFlag since "rename" has been deprecated and
this flag will be used as a placeholder for various other flags.
- Introduce new export flag in manifests
By default, files with the prefix "/bin/", "/usr/bin/" and "/usr/local/bin/"
will have a new export flag "x" in the 4th byte of the flag section of the Manifest.
The user can override this by using a new keyword "un-export()" in
the bundle definition file.
E.g. un-export(/usr/bin/file2)
Fixes #708
=> Export flag

builder/bundles.go
Fixes #719
Existing dnf cache contents can cause dnf queries to retrieve stale
package metadata. Cleaning the dnf cache before using it prevents old
cache contents from altering query results.
=> Clean dnf cache before using it

builder/build_validate.go, builder/repo_control.go
Newer versions of DNF require that yum repos are initialized, so Mixer
must initialize the local repo, even when it's empty.
Fixes #731
=> Initialize local yum repo

swupd/filesystem.go
Currently, mixer build update performs multiple hash calculations for each file in the chroot.
Every manifest file entry and subtracted file will have their hashes calculated.
It would be a significant performance improvement to calculate the hash one time for each file and re-use it.
fixes #585
=> Calculate file hashes once

builder/format.go, mixer/cmd/build.go
When a downstream mix crossed multiple upstream format bumps, the
upstreamversion and mix state variables were updated in the workspace,
but the changes were not updated in memory. This change reloads the
upstreamversion when it is staged/unstaged and reloads the mix state
after crossing each format boundary. Additionally, this change
increments the format number for each upstream format that the
downstream mix crosses.
Fixes #688
=> Update mix variables when crossing upstream formats

builder/build_validate.go, builder/bundles.go
By creating a separate installroot for each package resolving goroutine,
dnf can run in parallel without contention on the lock file when
accessing the dnf cache. Now, package and file resolution occurs within
the same installroot so that the dnf cache that was fetched when resolving
packages can be re-used when resolving files.
Fixes #730
=> Parallelize bundle file resolving

builder/build_validate.go
when bundle is deleted from a mix, bundle info file is not generated for that
bundle. When parsing the manifest if bundle info is empty, consider that
bundle to be deleted in the mix and do not resolve packages for that
bundle during build validation process. 
fixes #743
=> Handle MCA bundle deletion during format bump

bat/tests/content-chroot/run.bats
Currently, the "content-chroot" bat test is failing even locally due to permission issue. 
This PR fixes the issue for local runs.
It still fails in Travis for other reasons which is still being investigated.
=> Fix permission issue in bat test

.github/workflows/ci-tests.yml
Update github actions to v2 to handle re-runs.
Also, introduce a timeout of 30 mins for each job.
=> Update github actions to v2

builder/builder.go, docs/mixer.build.1, docs/mixer.build.1.rst, mixer/cmd/build.go
Mixer will now always update the LAST_VER file after `build update`.
This file is used by `build validate` (MCA) to determine whether
the version in comparison is a +10.
Fixes #735
=> Remove the --no-publish flag

Makefile, docs/mixer.init.1, docs/mixer.init.1.rst
Update man page to include `format` flag.
Also, update Makefile to build man pages as a prerequisite for the `build` target.
Fixes #557
=> Update man page to include `format` flag.

log/log.go
Reduce cluttering the logs by logging command tags only for the external
applications used within Mixer.
=> Log command tags only for external applications

builder/deltapacks.go, swupd/packs.go
While creating delta packs, only possible delta files are found.
If delta file is not found, log the error in debug mode instead
of generating warning, as delta might not have been
created for valid reason.
fixes #628
Signed-off-by: Ashlesha Atrey ashlesha.atrey@intel.com
=> Fix generated warning for delta packs

config/state.go
To avoid misleading info, indicate the correct warning message for
missing state file. Write the details of the default state values as
debug messages.
Fixes #491, #532
=> Update warning message for missing state file

builder/bundles.go
This change has proven to cause unnecessary churn for the bundle
tracking files when their contents ended up not being consumed by any
tools.
This reverts commit 6f840d712e77595abf4035c865a2b080731cf083.
=> Revert recent change to populate tracking files

mixer/cmd/root.go
When mixer's -c/--config option was used, the referenced config was read
too late to set a default log location. As a result, the log location
was always set to the empty string (disabling logging), that is, unless
--log VALUE was specified, or if mixer's current working directory
contained a builder.conf with LOG defined.
The root cause of this bug is an order-of-operations issue with cobra
integration; fix the issue by setting the log location in
PersistentPreRunE() instead of init(), ensuring that the command line
arguments have been processed, with `configFile` being set to the
-c/--config value if specified.
=> Fix setting of log location with custom config

swupd/packs.go
we need to not return "nil" if a delta file is missing, because that causes the caller
to not use the fallback option (which would include the full file)...
and we need the fallback option to have a complete pack
Signed-off-by: Arjan van de Ven <arjan@linux.intel.com>
=> fix missing files in packs

swupd/packs.go
this is triggering a client bug; lets revert until we get to the bottom of that
This reverts commit 73bf833128353c94d1ba44a8e1fc6674318f890b.
=> Revert "skip pure renames"

swupd/delta.go, swupd/packs_test.go
in https://github.com/clearlinux/mixer-tools/issues/782 a funky issue is found where
we do not use the right versions for delta files in some cases.
A full fix is complicated, but the client IGNORES the versions! so we can just hardcode
the versions to anything (10 and 20 here) and it'll suddenly resolve itself
=> Pin the from/to versions in the delta filename

swupd/create_manifests_test.go, swupd/files.go, swupd/files_test.go, swupd/heuristics.go, swupd/heuristics_test.go, swupd/manifest.go, swupd/manifest_test.go
This change allows for a chroot with specific versioned content with matching optimization levels to be added and accounted for. The paths will be stripped of a version prefix (currently /V3 or /V4) and the file's Modifier will be setup accordingly. The modifier will then be updated to reflect the optimization level of the file and the total optimization of any file with the same path.
With this change the previous Modifier setting has been revamped and the old 'C', 'b' and 's' fields will be ignored. The 'b' posed a slight problem that needed to be accounted for with how ghosted files are detected and this has been done through looking only at the files path.
=> [WIP]: Enable multiple versions of the same path

swupd/manifest.go
The codebase uses sortFilesVersionName prior to writing out manifests and that should be used in setupModifiers as well.
=> Use sort with version in setupModifiers

swupd/files.go, swupd/heuristics.go, swupd/manifest.go, swupd/manifest_test.go
If the modifiers of a file indicate it came from a chroot path, reset the filename to use the chroot path when reading the file information from a manifest.
Also ensure the only case files are marked as deleted is when it is the SSE file. Other optimized files marked as deleted will be skipped from being output in the manifest (and if the delete is new, the other files with the same post processed path will be marked as new in the version being built to ensure the deleted file is replaced).
=> Reset name from manifest based on modifiers

swupd/manifest.go
As other mixer processes might use the manifests after they are written, reset the path to include the prefix once the manifest write is complete.
=> Reset prefix after manifest is written

swupd/files.go, swupd/manifest.go, swupd/manifest_test.go
The optimized prefix doesn't set Misc flags until the last moment during manifest writing so ignore the flags when testing for peers when a prefix is in place.
Also improve some comments and test cases.
=> Add linking for optimized prefixes

go.mod, go.sum, vendor/github.com/rivo/uniseg/grapheme.go, vendor/github.com/rivo/uniseg/step.go, vendor/modules.txt
Move to go version to 1.21 (1.22 is still early and 1.21 has a long chain of stable releases).
Also update dependencies to latest their versions.
=> Update go version and re-vendor

Makefile
The package has been rst2man for long enough, switch the Makefile to use the "new" name.
=> Rename rst2man.py to rst2man
